### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by tkkcc** [ms-jpq/coq_nvim#10]
Yes, It's fast. But I still have some questions:

1. How to define user snippets?
1. How to auto expand completion on `tab`?
1. Relative path not starting with `./` can not trigger path completion. But `<c-x><c-f>` can. For example in home directory, type `.config/` then `<c-space>` won't suggest paths.
1. Path completion does not work well with upper case character. For example `./.config/b` suggests `./.config/BaiduPCS-Go/`, but `./.config/B` does not.
1. In python, `<c-space>` is needed when importing each package and the first two modules. For example `from torch import abs, cuda`. Can this be automaticly triggered.

Thanks!

**Comment by ms-jpq** [comment]
hey, i am still working on this, you are using a pre-release :)

those are good questions though, and unfortunately i will not be adding in user snippets for a bit, that will go in the 1.1 release.

i dont get question 2, do you press tab for completion? i am using the <c-space> key for it if thats what you are asking for

and the path thing yeah, i am going to work more on that one.

over all though, thank you for discovering this organically and i hope its been ok thus far :)

my timeline for finishing this is hopefully with in the next two weeks

**Comment by ms-jpq** [comment]
for the relative path one, I would not change how it behaves, because it triggers on every keystroke and not just on a specific hotkey.

it would be super annoying to have `.eslint`, `.gitignore`, `.dockerignore` etc  pop up every time you typed in `.` imo,

**Comment by rafamadriz** [comment]
Hey @ms-jpq thanks for your work, this looks awesome. I just have one question:

- does this uses the builtin lsp api of neovim ? or you did you create your own implementation like other plugins already do ?

**Comment by ms-jpq** [comment]
it uses nvim API, I cant write an LSP client in python, not part time anyways.

If I wrote it in node and used the microsoft packages then yes. But then i'd be writing a `coc.nvim` competitor and even if I do 10x better nobody would use it.

I am also a major "not invented here" person, so basically all the code used here is written by me, except the `nvim api client`, which would be redundant.

**Comment by ms-jpq** [comment]
@tkkcc i fixed the path thing,

and thank you for randomly finding my plugin and commenting on it, without you I'd put another 2 month of work into this and scope-creeped even more and since you used it I might as well ship it now

once I fix the initial bugs im gonna go get a drink or something to celebrate lmao, its been such a huge part of my life for the past year

**Comment by rafamadriz** [comment]
> it uses nvim API, I cant write an LSP client in python, not part time anyways.
> 
> If I wrote it in node and used the microsoft packages then yes. But then i'd be writing a `coc.nvim` competitor and even if I do 10x better nobody would use it.
> 
> I am also a major "not invented here" person, so basically all the code used here is written by me, except the `nvim api client`, which would be redundant.

okay that makes sense, I was just wondering and since there's no mention of this in the README I wanted to ask. May I suggest mentioning this in the README ? So people are aware that this plugin uses the neovim lsp api.  

Also, I don't see any mention on how to setup the LSP completion, is having the server in your $PATH enough ? What happens if I have it installed in a specific PATH and want to point the command that coq_nvim executes for the server to that very specific PATH ?

**Comment by ms-jpq** [comment]
you need to install the [Nvim Official LSP integration](https://github.com/neovim/nvim-lspconfig),

good idea to put in the documentation though.

sorry I am not going to do a write up in my own docs because I think the official source is better :D

**Comment by rafamadriz** [comment]
> you need to install the [Nvim Official LSP integration](https://github.com/neovim/nvim-lspconfig),
> 
> good idea to put in the documentation though.
> 
> sorry I am not going to do a write up in my own docs because I think the official source is better :D

ohhh I see know, sorry I was just a bit confuse and asking stupid question. You're 100% right the official docs are more than enough. I got confuse for a moment thinking that I needed specify LSP sources for coq or something. But now I got it, this is similar to compe.nvim which is what I'm currently using, this plugin will automatically autocomplete from LSP if the server is attached. Sorry for those unnecessary questions.

**Comment by ms-jpq** [comment]
nono its ok im glad to answer :D im nice <3

**Comment by tkkcc** [comment]
Thanks for rely. I just search recently updated repo to find one plugin better than compe. But I am still on compe now.

For completion on relative paths not starting with `./`. coc, vscode and compe support it partially. There is no need to trigger path discovery and suggestion on dot, but maybe on `%a/`。Here is how compe does:
![Peek 2021-08-15 15-31](https://user-images.githubusercontent.com/17373509/129470713-5cb57876-51d3-4881-ba3b-829213c6a2f2.gif)

For auto expand completion on tab. I mean the buffer will be changed simultanously when selecting candidates by pressing tab. This is default in compe:
![Peek 2021-08-15 15-21](https://user-images.githubusercontent.com/17373509/129470475-f9cd08fe-cf4e-4906-8b34-8815084c6c3c.gif)
I can't say this is a must, but a habit for some people.

For the upper case bug, I tried on 70c78dc, but it's still:
![Peek 2021-08-15 15-34](https://user-images.githubusercontent.com/17373509/129470808-0cbea5ec-7f41-4a30-a4f3-aed93e304789.gif)




For the python import issue. Some slow lsp suggestions can be timeout, thus never show. Here the `cuda` suggestion needs manually trigger by pressing `<c-space>.
![Peek 2021-08-15 15-53](https://user-images.githubusercontent.com/17373509/129471349-5aacded8-46d3-4103-894e-fdfc27fdfa89.gif)




But compe support auto updating, so it's easier and faster in my experience:
![Peek 2021-08-15 15-55](https://user-images.githubusercontent.com/17373509/129471431-cf2d713a-6ad5-4a86-b33d-31cf0154cae8.gif)

I clearly know this plugin is in development state. Just be relax and enjoy development. <(≧▽≦)>

**Comment by ms-jpq** [comment]
thank you for the detailed feedback, i will go and see what I can do tomorrow, its fairly late where I live and my brain cells are on strike rightn ow

**Comment by iverberk** [comment]
Hi @ms-jpq, thanks for this very nice plugin. I would also be interested in having the buffer automatically update with the currently highlighted/selected item in the completion menu when using tab to navigate the completion menu. Can this be an option?

**Comment by zeertzjq** [comment]
> Hi @ms-jpq, thanks for this very nice plugin. I would also be interested in having the buffer automatically update with the currently highlighted/selected item in the completion menu when using tab to navigate the completion menu. Can this be an option?

There is some discussion about this in #90

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/176

this one improves the import heuristics

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/177

this one fixes the upper case path matching.

**Comment by ms-jpq** [comment]
ok now we have something like a preview text too 👍 

![nice.gif](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/pretty.gif)
