### ISSUE TITLE
Filtering seems too fuzzy and doesn't refine much when typing

### ISSUE THREAD

**Issue by MaienM** [ms-jpq/coq_nvim#100]
The suggestion order is unexpected and counterintuitive to me, and typing more to help it figure out what I want is not nearly as effective as I would have hoped. Here's an example where I'm trying to complete a field name that is provided by LSP.

![2021-08-19-145059_680x71_scrot](https://user-images.githubusercontent.com/583129/130203112-abb6896e-86f2-4995-94f0-429db659a00f.png)

I first type the first 4 characters of this field, which results in it being in 3rd place. The 1st and 2nd place are not particularly sensible given the context, but they do contain the same characters in the same order so I can kind of see how this happens. Not what I'd expect and somewhat annoying, but let's try adding some more characters.

![2021-08-19-150328_615x69_scrot](https://user-images.githubusercontent.com/583129/130203132-8b44e17d-b675-4542-a827-3f718f9158ff.png)

By now I've typed most of the field name and it is STILL ranked below the other two options, even though those contain less than half of the typed characters at this point.

This just doesn't make sense to me. It's fine that the filtering/sorting doesn't always immediately get it right, but when I then proceed to give it (quite a lot) more to refine this filtering it doesn't improve _at all_. It feels like the filtering/sorting is just ignoring my extra input. How are either of the first two results still suggestions at this point?

I've tried to play with the weights a bit to see if I could tune this, but I feel I have to be pretty heavy-handed with this. Setting `prefix_matches` to `4` makes it do what I want in the second case, but still only once I've typed half of the field name myself. Setting it to `10` gets it to figure out what I want after `conta` which is okay, but that's quite a deviation from the defaults and I fear this might throw things off in other cases. If I want it to figure out my intent in the first case I presented I need to bump it all the way to `30`.

The changes you propose in #92 might help with this by bumping the weight of all LSP items, but even without that I still feel like it could do a better job here, especially in the second example.

---

One thing to add is that reopening the completion with `<C-space>` can in some cases get it to figure it out quicker, but not by much and not without changing the weights. And sometimes it gets worse doing that (default weights were used for this)

![2021-08-20-103844_596x50_scrot](https://user-images.githubusercontent.com/583129/130206015-650613b4-ac1e-474b-b1d1-41c5168d4df3.png)

**Comment by ryanbas21** [comment]
I found a similar pain and I just removed the snippets. It wasn't worth it to me to have ranking like this and not get the auto completion.

If this is fixed then the snippets could be worth it.

**Comment by ms-jpq** [comment]
I just made the fuzzy search slightly more strict, but I think you are right more should be done on this end.

maybe you want to increase the `coq_settings.match.fuzzy_cutoff`.

I will think about this more

**Comment by ms-jpq** [comment]
I assume @MaienM  is using Typescript Language server in the screenshots. 

The third picture is atrocious, and its because for LSP sources, I purposefully made the rules more lax for filtering and such.

My hope was that LSP servers should be given greater latitude to do their own ranking and such, but the Typescript LSP seems to just barf out every symbol under the sun, and goes like "heres 4000 results, the client can filter".

I should figure out how to rectify that

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/110

---

##### `coq_settings.clients.<x>.weight_adjust`

Weight adjustment for ranking, normalized to `[0.5, 1.5]` using `S(x) = 1 / (1 + e^-x) + 0.5`

Ideally pick a number between `[-2, 2]`.

`S(0) = 1` no adjustment

`S(-2) ~= 0.6` anything smaller has diminishing returns

`S(+2) ~= 1.4` anything bigger has diminishing returns

---

Right now all the weight adjustments are set to 0, meaning no adjustment. 

I will just push out this for now, and figure out good guesstimate defaults this weekend.

**Comment by ms-jpq** [comment]
added default weights. will re-open this if people complain about them not being good enough

**Comment by gsuuon** [comment]
I'm still getting pretty confusing ranking results with rust-analyzer, even with `weights.prefix_matches = 30.0`:
![image](https://user-images.githubusercontent.com/6422188/155246878-f8864761-2ee5-4bc8-98d2-2dcd7e074dd2.png)
![image](https://user-images.githubusercontent.com/6422188/155246858-1d0d3b23-7d0b-42c0-b75d-1faeeb99b780.png)

If I turn off lookahead with `match.look_ahead = 0` then I get the expected exact match first.

**Comment by rajaravivarma-r** [comment]
@gsuuon Thanks. Setting the `match.look_ahead = 1` value almost solved all of my completion problems. I'm so spoiled by fzf completions.
