### ISSUE TITLE
Not an issue, just asking...

### ISSUE THREAD

**Issue by massisenergy** [ms-jpq/coq_nvim#105]
....cause I do not know where to post enquiries. Sorry for that!

Is it possible that it would automatically look for commands specific to a particular software & provide completion/ suggestion?

Here my point of interest is OpenFOAM (object oriented C++). 
- https://cfd.direct/openfoam/
- https://cpp.openfoam.org/v9/index.html
- https://www.cfd-online.com/Forums/openfoam-programming-development/207186-openfoam-youcompleteme.html#post707518
- https://github.com/rdnetto/YCM-Generator

This question is same but for vim, I want to know if coq_nvim adds similar functionalities to neovim.

**Comment by ms-jpq** [comment]
like bash or zsh completions? 

imo, thats the LSPs job.

for example:

[bashls](https://github.com/bash-lsp/bash-language-server) or [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices)
