### ISSUE TITLE
COQ breaks `CTRL-X_CTRL-V`, `CTRL-X_s`, etc.

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#111]
Steps to reproduce COQ breaking `CTRL-X_CTRL-F`:
1. Open an empty buffer
2. Run `:COQnow`
3. Type a part of a command
4. Press `CTRL-X_CTRL-V`
5. A popup menu opens and then closes immediately

Steps to reproduce COQ breaking `CTRL-X_s`:
1. Open an empty buffer
2. Run `:COQnow`
3. Run `:set spell`
4. Type a part of a word
5. Press `CTRL-X_s`
6. A popup menu opens and then closes immediately

**Comment by zeertzjq** [comment]
Maybe this is impossible to fix unless auto completion is disabled. Closing this for now. Maybe I'll reopen later (probably after #44 is solved).

**Comment by zeertzjq** [comment]
I think I have a solution for this. #135

**Comment by ms-jpq** [comment]
fixed thanks to @zeertzjq
