### ISSUE TITLE
Snippets don't match patterns starting with backslash

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#112]
Steps to reproduce:
1. Open an empty `.tex` file
2. Run `:COQnow`
3. Type `\documentclass`
4. Press `<Tab>` until the snippet mentioned below is selected
5. Press `<CR>`
6. `\\documentclass[]{article}` appears in the file instead of `\documentclass[]{article}`

This can be found in `coq+snippets.json`:
```json
        {
          "content": "\\documentclass[${1}]{${2:article}}${0}",
          "doc": "",
          "grammar": "snu",
          "label": "",
          "matches": {
            "\\documentclass": true,
            "documentclass": true
          },
          "options": {}
        },
```

**Comment by ms-jpq** [comment]
thanks! good catch! i will fix tmr afternoon

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/120
