### ISSUE TITLE
Cursor position post completion using "." and "("

### ISSUE THREAD

**Issue by nymann** [ms-jpq/coq_nvim#121]
**Expected**
When completing using `.` or `(` we want to be in `<inset-mode>` one character to the right of the used completion key.

**Actual**
We end up being in `<insert-mode>` in front of the completion character (to the left).

![record](https://user-images.githubusercontent.com/7005867/130334683-16e2bdc3-771b-4f46-803d-bf94119cba80.gif)

**Comment by mcchrish** [comment]
Same as https://github.com/ms-jpq/coq_nvim/issues/113. It happens with any character and other inputs.

**Comment by ms-jpq** [comment]
hummmmm, is this even possible to fix without mapping every single key?

i will need to think about it

**Comment by ms-jpq** [comment]
wait was this good before? I remember this not being broken, werid, if it wsant broken before then i could probably fix it, but i cant think of how i broke it tho

**Comment by mcchrish** [comment]
@ms-jpq it's certainly working before.
I tried going back to this commit: e6a8b05d34bdc9810232fbb1c4e77631239d9b78 and look:

https://user-images.githubusercontent.com/7200153/130559012-57410288-105f-45b7-b1de-cf1b5b10824f.mov

**Comment by ms-jpq** [comment]
thank you im looking at this right now, hummm i wonder what i did

**Comment by ms-jpq** [comment]
found it, because I need to do a resolve for LSP imports, the `.` or whatever key have you is entered before the LSP has a chance to respond.

https://github.com/ms-jpq/coq_nvim/issues/71


hummmmmmm, probably can just prevent the key from being entered, save the key, and restore it.

l0l, this sucks, really ugly

**Comment by mcchrish** [comment]
The example I've shown doesn't involve LSP though, just plain buffer completion.  I don't know much on how the coq internals work, but is it possible for coq skip the resolve phase if the completion does not involve LSP imports? Maybe that could simplify things a bit. VSCode seems to know:
<img width="479" alt="Screen Shot 2021-08-24 at 2 18 07 PM" src="https://user-images.githubusercontent.com/7200153/130566487-248cf04c-9482-4cfd-9836-726394c2cd40.png">

edit: I guess coq knows about it too:
<img width="245" alt="Screen Shot 2021-08-24 at 2 26 06 PM" src="https://user-images.githubusercontent.com/7200153/130566993-88580755-7798-4915-b2d2-fef7777229ed.png">


Another idea perhaps is to activate auto import only on `<cr>` but not everyone might like the idea.

**Comment by ms-jpq** [comment]
I am doing an overhaul of the edit system, might take a while for the PR, like until tmr night.

dw 👍 


thank you for the help!

**Comment by zeertzjq** [comment]
How do you make `.` and `(` accept the completion? I cannot make it work.

**Comment by zeertzjq** [comment]
Currently the edits are always performed asynchronously. Maybe they can be performed synchronously when cheap?

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/147

PR here

**Comment by zeertzjq** [comment]
This seems to just remove the extra chars, and only work if cursor is at the end of the line.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/148/files#diff-f8e73281ee05d0e11af677928526cf4364dd117ba8384ee3e03cc84458e86ebf

will fix the only at end of line thing, I realized after I pushed PR.

---

i dont think im gonna make it insert the extra char tbh, maybe, idk

**Comment by zeertzjq** [comment]
Theoretically anything can happen between `CompleteDone` and `edit()`, including any text change and cursor movement, so this can indeed be tricky.

**Comment by ms-jpq** [comment]
`trans_inplace` actually does something fun, it calculates the necessary instructions to do step by step transform of `src -> dest`, so at least within the same line, its accurate.

**Comment by ms-jpq** [comment]
anything else is no promises, but it should just work for vast majority of cases.

**Comment by mcchrish** [comment]
I'd argue the extra character should be inserted.
When I type `conso` and selected `console` then by pressing `.` the result should be `console.`. It's how every other completion plugin I've tried works.

Digging a little bit more, LSP have an optional spec called `commitCharacters`, which surprisingly is the exact thing that we are discussing from the start. https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItem

```
/**
	 * An optional set of characters that when pressed while this completion is
	 * active will accept it first and then type that character. *Note* that all
	 * commit characters should have `length=1` and that superfluous characters
	 * will be ignored.
	 */
	commitCharacters?: string[];
```

And it looks like cmp supports it now too: https://github.com/hrsh7th/nvim-cmp#concept

**Comment by mcchrish** [comment]
I'm thinking if there is a consistent behavior that should be followed is this:
- Completion is only committed by `<cr>` or any characters from `commitCharacters`
- Don't complete if any other characters

What do you think?

**Comment by ms-jpq** [comment]
@mcchrish I can't do that, not without remapping keys.

anyways I made it consistent, so it doesn't matter if the new char is at the end of line or not this will remove it.

---

I will close this issue for now and for @mcchrish, I will think about how to do this a good way. maybe as a toggle

**Comment by mcchrish** [comment]
> @mcchrish I can't do that, not without remapping keys.

That may just be the case. I peeked a little bit on how cmp does it and it seems to creates mapping for each character.

**Comment by ms-jpq** [comment]
> That may just be the case. I peeked a little bit on how cmp does it and it seems to creates mapping for each character.

ok I definitely would rather not do that lol, remapping each character breaks down as soon as somebody uses a keyboard you don't expect, and probably will introduce lots of weird edge cases too.

thanks for the investigation! :D

**Comment by mcchrish** [comment]
What do you think of `InsertCharPre` autocmd? Sorry, I'm just putting whatever idea I can find but not able to help much 😅

**Comment by zeertzjq** [comment]
> What do you think of `InsertCharPre` autocmd? Sorry, I'm just putting whatever idea I can find but not able to help much sweat_smile

I think `InsertCharPre` is triggered before `CompleteDone`, so it won't work.

**Comment by zeertzjq** [comment]
Maybe `InsertCharPre` can work. Try [branch `insert-char-pre` of my fork](https://github.com/zeertzjq/coq_nvim/tree/insert-char-pre).

**Comment by ms-jpq** [comment]
interesting, you are accumulating all the chars.

hummm

**Comment by zeertzjq** [comment]
> Maybe `InsertCharPre` can work. Try [branch `insert-char-pre` of my fork](https://github.com/zeertzjq/coq_nvim/tree/insert-char-pre).

It seems to break Insert mode mappings that Insert characters.

**Comment by zeertzjq** [comment]
I just found the accumulating is completely unnecessary. Just counting is enough.

**Comment by zeertzjq** [comment]
> Maybe `InsertCharPre` can work. Try [branch `insert-char-pre` of my fork](https://github.com/zeertzjq/coq_nvim/tree/insert-char-pre).

This solution is completely meaningless. `InsertCharPre` is not required at all. Removing the branch.
