### ISSUE TITLE
disable "no snippets loaded" message

### ISSUE THREAD

**Issue by goolord** [ms-jpq/coq_nvim#123]
i don't care if snippets aren't loaded, snippets r dumb
⠀ ⠀⠀ ⠀                 ⠀        🤠
　　　 💯 💯 💯
　 　💯 　💯　💯
　  👇🏽　  💯💯　👇🏽
　　　 💯　  💯
　　　💯　　💯
　　　 👢　　👢

**Comment by goolord** [comment]
ok it goes away with
 ```lua
vim.g.coq_settings = {
  ["clients.snippets.enabled"] = false
}
```
my bad

**Comment by issadarkthing** [comment]
Where do u put that in the config?

**Comment by goolord** [comment]
```lua
vim.g.coq_settings = {
  ["clients.snippets.enabled"] = false
}
```
