### ISSUE TITLE
Is it possible to use recommended key mapping and override specific values?

### ISSUE THREAD

**Issue by pauldthomson** [ms-jpq/coq_nvim#124]
It seems as soon as I configure a keybinding, the default `keymap.recommened = true` is gone, even if I set it such as:
```
vim.g.coq_settings = { 
    auto_start = 'shut-up', 
    keymap = { 
        recommended = true,
        jump_to_mark = '<c-m>' 
    }
}
```
It's also highly possible I'm making a mistake in my usage. 
I want to override the `jump_to_mark` as I use https://github.com/christoomey/vim-tmux-navigator so <c-h> navigates vim/tmux splits, which gets overridden with the default keymap here. But setting just that value seems to blow some other stuff away as for example, trying to open a file from the quick fix window gives me an error: `No more marks available`. Works as expected if I remove the keymap settings above.

**Comment by zeertzjq** [comment]
Neovim cannot distinguish `<C-m>` and `<CR>` . Try mapping another key like `<C-q>` instead. This has nothing to do with this plugin.

**Comment by pauldthomson** [comment]
Thanks, sorry for the confusion.
