### ISSUE TITLE
Auto start not working

### ISSUE THREAD

**Issue by copypasteonly** [ms-jpq/coq_nvim#129]
Complete beginner to neovim here, was trying to put
'let g:coq_settings = { 'auto_start': v:true | 'shut-up' }'
in my init.vim but this is what it says
Error detected while processing /home/denzel/.config/nvim/init.vim:                                      
line   26:                                                                                               
E722: Missing comma in Dictionary: | 'shut-up' }                                                         
E15: Invalid expression: { 'auto_start': v:true | 'shut-up' }

This is my init.vim

`source $HOME/.config/nvim/vim-plug/plugins.vim
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set nohlsearch
set hidden
set noerrorbells
set incsearch
set scrolloff=8
set signcolumn=yes
set clipboard+=unnamedplus
set relativenumber
set mouse=a
let mapleader=" "
map <F12> :w <CR> :!gcc % -o %< && ./%< <CR>
colorscheme catppuccino
nnoremap Y y$
lua << EOF
local lsp = require "lspconfig"
local coq = require 'coq'
require'lspconfig'.pyright.setup{}
require'lspconfig'.ccls.setup{}
EOF
let g:coq_settings = { 'auto_start': v:true | 'shut-up' }
" Find files using Telescope command-line sugar.
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

" Using Lua functions
nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>
nnoremap <leader>fg <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>`

Sorry if this is a dumb question as I have just started setting up nvim yesterday and yet to this day still not understood most of it

**Comment by ms-jpq** [comment]
please use either `{ 'auto_start': v:true }` or `{ 'auto_start': 'shut-up' }` :)

**Comment by copypasteonly** [comment]
> please use either `{ 'auto_start': v:true }` or `{ 'auto_start': 'shut-up' }` :)

Thank you so much, I'm too stupid lol.

**Comment by ms-jpq** [comment]
no wworries <3
