### ISSUE TITLE
Cannot Enter on quickfix list or location list

### ISSUE THREAD

**Issue by tung-tinypulse** [ms-jpq/coq_nvim#136]
Please view my record here
https://asciinema.org/a/EqHmrLmv4vGUHLjJNgWRrgLlj

It happens with both quickfix list and location list. It shows "No more marks available" message. 

![image](https://user-images.githubusercontent.com/21326910/130891976-3895382e-caee-4a16-a97a-884f9552fa7b.png)

**Comment by ms-jpq** [comment]
can you please try

`let g:coq_settings = { 'keymap.jump_to_mark' : '' }`

I suspect this is a mapping conflict with the default hotkey `<c-h>`. If removing it helps, you can remap the default hotkey to something else,

**Comment by tung-tinypulse** [comment]
Set the keymap `'keymap.jump_to_mark' : ''` fixed this issue. But when I map it to another key (`<c-m`), the issue occurs. Thanks for your quick response.

**Comment by ms-jpq** [comment]
pretty sure `<c-m>` is actually `<enter>`, try it `bash` for example:

`echo 555 <c-m>` prints out 555

**Comment by tung-tinypulse** [comment]
Oh I didn't know that. I remap to `<c-n>` and it works fine now. Thank you for your help.
