### ISSUE TITLE
Feature: Pum icons for LspKind and source

### ISSUE THREAD

**Issue by ray-x** [ms-jpq/coq_nvim#138]
There is a placeholder in default.yml.  display.pum.icons
I am wondering how to map the LspKind and Source to nerfont icons/emoji
e.g. 
display.pum.icons = {'Function': 🅕, 'treesitter': 🌴}

**Comment by ms-jpq** [comment]
duplicate of https://github.com/ms-jpq/coq_nvim/issues/87

I will start work on that soon 👍

**Comment by ms-jpq** [comment]
![icons.png](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/icons.png)

**Comment by ray-x** [comment]
Thanks!
Is it possible to show the icon only? That will give move spaces in the popup menu.

e.g.
![image](https://user-images.githubusercontent.com/1681295/131440982-9086c795-eea8-4f87-aafd-f2b564e568fb.png)

**Comment by ms-jpq** [comment]
`let g:coq_settings = { 'display.icons.mode': 'short' }`

:)
