### ISSUE TITLE
[Feature] nvim-lua as a source

### ISSUE THREAD

**Issue by ray-x** [ms-jpq/coq_nvim#139]
Would be great to enable autocomplete for neovim lua APIs in coq and here is how `compe` did it.

https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe_nvim_lua/init.lua

**Comment by ms-jpq** [comment]
this is the LSP's job IMO, I think eventually I would like to write an LSP at some point, but until then I will close this for now.
 sorry

**Comment by zeertzjq** [comment]
<https://github.com/folke/lua-dev.nvim> can provide completion for Neovim Lua APIs.

**Comment by ray-x** [comment]
Some of the neovim api can be provided by LSP. But some of the API can not.
The reason behind is that those lua APIs were exposed from C API. Those C APIs do have associated lua file and will not be parsed by lua-language server. One example is `vim.fn.append()`, there is no lua function append().

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq.thirdparty

![uwu.gif](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/nvim_lua.gif)

**Comment by ray-x** [comment]
That is great!!! Thanks!
