### ISSUE TITLE
Wrong range replaced when autocompleting with TexLab

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#141]
When autocompleting with TexLab a wrong range is replaced:

https://user-images.githubusercontent.com/35768171/131077426-365dbd4e-2a0c-4bc6-80b1-8695211a7e88.mp4

Doesn't happen when completing manually (note the `Ctrl+␣`):

https://user-images.githubusercontent.com/35768171/131077455-dc844a82-3dc5-46aa-b772-266fb0ec8d2c.mp4

The only settings I have changed from default are those related to display and keymap.

Changing auto resolve timeout (even to a very large value) doesn't seems to change the behavior.

**Comment by ms-jpq** [comment]
I think this is a case of LSP error:

I noticed the exact same thing happening for `\documentc<enter>`

---

if you set env variable `COQ_DEBUG=1` it will show you what was send to you by the LSP:

```python
((RangeEdit(new_text='documentclass', begin=(0, 1), end=(0, 5), encoding='UTF-16-LE'),),
 [EditInstruction(primary=True, primary_shift=False, begin=(0, 1), end=(0, 5), cursor_yoffset=0, cursor_xpos=14, new_lines=['documentclass'])])
```

---


and for `\docu<enter>`

```python
((RangeEdit(new_text='documentclass', begin=(0, 1), end=(0, 4), encoding='UTF-16-LE'),),
 [EditInstruction(primary=True, primary_shift=False, begin=(0, 1), end=(0, 4), cursor_yoffset=0, cursor_xpos=14, new_lines=['documentclass'])])
```

---

In both cases the `end=(<row>, <col>)` is too early and ends up splicing into the middle of your word.

**Comment by ms-jpq** [comment]
`RangeEdit` is the instruction sent by the LSP, `EditInstruction` is used by `coq` internally, to calculate position of cursor, and stuff with edits applied.

Basically all the LSP stuff get translated into `EditInstruction`, regardless if they have a `range` specified to them or not.

There is an easy fix to this however, and its to basically ignore `range` for LSPs for edits that's under the cursor, which is a blanket thing, that might make other LSPs less useful as a trade off.

**Comment by ms-jpq** [comment]
What I can do is add something like a compatibility mode for LSP servers that do not give like have good results, I can actually get the LSP server names and let users specific whether to turn those mode on for servers individually 

Ill add that to to todo list

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/162

I think i fixed it

**Comment by zeertzjq** [comment]
Indeed.
