### ISSUE TITLE
Can I move the list menu?

### ISSUE THREAD

**Issue by miroci** [ms-jpq/coq_nvim#142]
I would like to know if there is a way to move the list window to another position, for example 30px forward (to the right)?

**Comment by Shougo** [comment]
What is the list window?
The screenshot is recommended.

**Comment by miroci** [comment]
![scre](https://user-images.githubusercontent.com/48184639/131143031-3bc86ad5-c6d5-4c30-8fdd-203efca4052a.png)
I just want to move that to another position, how can I?

**Comment by ms-jpq** [comment]
i don't think vim lets u do that, i can probably move it to the left by fiddling around with the `complete` items, but not to the right, hummm

**Comment by Shougo** [comment]
It is Vim/neovim feature unfortunately.

**Comment by ms-jpq** [comment]
yeah sorry ill close this one, thank you for backing me up @Shougo
