### ISSUE TITLE
Feature request: show function signature when inputting parameters

### ISSUE THREAD

**Issue by quantum-booty** [ms-jpq/coq_nvim#149]
Currently to see the function signature I have to press tab:
![image](https://user-images.githubusercontent.com/28958399/131232778-0c00ffd4-f551-40c1-8b1a-dfd9f020e204.png)
However as soon as I start typing the function signature disappears. It would be nice to see them as I'm inputting the parameters.
Something like this:
![image](https://user-images.githubusercontent.com/28958399/131232914-0b18bac4-8423-42a8-ae0f-ff2dbd8dfd2b.png)

**Comment by ms-jpq** [comment]
empty request haha :p

**Comment by quantum-booty** [comment]
@ms-jpq Sorry I added the title.

**Comment by zeertzjq** [comment]
You may be interested in <https://github.com/ray-x/lsp_signature.nvim>

**Comment by ms-jpq** [comment]
thanks @zeertzjq , that plugin looks sick!

and yeah I will close this one since I don't really feel like its `coq`'s job to do everything.
