### ISSUE TITLE
Feature request: support modular sources

### ISSUE THREAD

**Issue by comploplo** [ms-jpq/coq_nvim#153]
support for external sources of completions from other repostories, similar to nvim-cmp, maybe even sources designed to work with cmp, would be excelent.

**Comment by comploplo** [comment]
Closed because it's a duplicate of issue #80

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/blob/coq/docs/CUSTOM_SOURCES.md

done,

its **even faster** than just using `vimtex`, `orgmode`, etc, because `coq` transparently  adds a layer of `sqlite` cache

**Comment by Mte90** [comment]
I was able to do it https://github.com/Mte90/coq_wordpress a custom one :-)

**Comment by ms-jpq** [comment]
nice!

btw

you can save a few lines of code I think

![图片](https://user-images.githubusercontent.com/50598611/133489751-11f6fbf3-3d96-4f6e-850d-d7f52ec507bd.png)

dont need to expand it youself :D

**Comment by Mte90** [comment]
Thanks I had some troubles to get the path of the plugin file so I had to do in that way.
