### ISSUE TITLE
`COQdeps` always installs latest pip and always finds pip 20.2.3

### ISSUE THREAD

**Issue by henriqpsantos** [ms-jpq/coq_nvim#154]
After updating COQ, it always tries to install pip 21.2.4, and always uninstalls 20.2.3, despite 21.2.4 already being installed on my system. I tried multiple times to reinstall pip 21.2.4, and it's even cached on my system, but it stubbornly always finds 20.2.3... Here's the result from pip --version:
`pip 21.2.4 from C:\Users\<USER>\AppData\Roaming\Python\Python39\site-packages\pip (python 3.9)`
And COQdeps sees this:
![image](https://user-images.githubusercontent.com/2131630/131250368-bff3122c-c914-4b7e-9b83-c05f76774c57.png)

**Comment by dnaaun** [comment]
This plugin creates a [virtual environment](https://www.google.com/search?q=python%20virtual%20environment) in a directory called `.vars/` under the installation location of the plugin itself, so it shouldn't affect your global python installation at all.

To verify, you can open a command line prompt and type in `python -m pip --version`. <sup>1</sup> It should show you both the version and location of the pip package installed in your global python installation, and the output after you run `COQdeps` should be identical to before.

<hr/>
<sup>1</sup> I don't use WIndows so I'm not entirely sure how one would find and run the global installation.

**Comment by ms-jpq** [comment]
what @davidatbu  said.

also good news:

treesitter got an overhaul! :D 

![ts.img](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/treesitter.gif)
