### ISSUE TITLE
Tailwind completion glitches

### ISSUE THREAD

**Issue by 0xDjole** [ms-jpq/coq_nvim#159]
From: Input "bg"
Selected "bg-gray-500"
Outputs "bg-gray-500g"

Sometimes it even adds more at the end of the completion.

Mixes the input with Selected basically..puts input at the end of selected value and creates mixed output..

**Comment by ms-jpq** [comment]
hummmmm, i fucked up the cache, sorry , brb

**Comment by 0xDjole** [comment]
noice

**Comment by ms-jpq** [comment]
please try now.

https://github.com/ms-jpq/coq_nvim/pull/162

**Comment by 0xDjole** [comment]
Works perfectly. The only one library doing this for tailwind is this one. Congrats!
