### ISSUE TITLE
Cannot import 'join'

### ISSUE THREAD

**Issue by ChrisAmelia** [ms-jpq/coq_nvim#18]
When typing  any command `:COQ`:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/share/nvim/site/pack/packer/opt/coq_nvim/coq/__main__.py", line 6, in <module>
    from shlex import join
ImportError: cannot import name 'join'

**Comment by ms-jpq** [comment]
oh thats cuz your python version is too old. sorry

https://docs.python.org/3/library/shlex.html

`join` is added in `python 3.8` and I guess yours must be older?

can you please update your python version, thanks <3

**Comment by Shougo** [comment]
I think to add Python version check is useful.

**Comment by Palpatineli** [comment]
I have the same issue since I have both python3.7 and python3.8 in the system. When I use nvim in a venv that needs to use py3.7, coq fails. Is it possible to call python3.8 explicitly so it's not affected by the env?

**Comment by ms-jpq** [comment]
I had a check for python < 3.8, but I guess it didnt work. so my latest PR added another check.

@Palpatineli 

I added the following to the FAQ:

"I want to use a different python version"

`vim.g.python3_host_prog=<absolute path to python>`

Note: ~/ will not be expanded to $HOME, use vim.env.HOME .. <path> instead.
