### ISSUE TITLE
Entering Insert mode then leaving immediately or typing the first character hangs for about one second in a very large C file

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#183]
This can be very hard to reproduce, as I can only reproduce it in a very large C file (9000+ lines). Maybe related to `_insert_enter()` (`COQinsert_enter`) as if I remove its corresponding `augroup` Neovim no longer hangs.

**Comment by ms-jpq** [comment]
might be tree_sitter, it parses on insert_enter.

and its known to hang on very large files.

**Comment by zeertzjq** [comment]
Adding `clients = { tree_sitter = { enabled = false } },` to `coq_settings` doesn't solve the problem.

**Comment by zeertzjq** [comment]
Typing the first character hangs as well.

**Comment by zeertzjq** [comment]
> Adding `clients = { tree_sitter = { enabled = false } },` to `coq_settings` doesn't solve the problem.

Now it solves the problem.

**Comment by ms-jpq** [comment]
what I am going to do is to add a timer to tree_sitter, if it takes like more than 0.2 seconds say, it will print out an error,

because it does have very atrocious performance.

its not really `coq`'s issue to fix, but we can make the UX better

**Comment by ms-jpq** [comment]
![图片](https://user-images.githubusercontent.com/50598611/131613613-59f4ee63-6017-4525-8c03-c9511ad813e7.png)

**Comment by ms-jpq** [comment]
the default warning threshold is like 200ms, i dont know if thats too high or too low.

but yeah lol, 48ms to parse like a simple 300 line python file, its a bit slow for my taste.

**Comment by ms-jpq** [comment]
@zeertzjq 

I improved it, I think now, if you don't edit those super large files frequently, the cost of having treesitter being slow is paid only once, it will disable itself on current buffer if it took too long

![图片](https://user-images.githubusercontent.com/50598611/131614439-bbff4608-fc75-4160-a409-cf2c1f4bdddb.png)

**Comment by ms-jpq** [comment]
@zeertzjq 

can you try re-enabling tree sitter,

I added more performance improvements, the following PR made it so that tree sitter only searches a limited amount of space instead of the entire document. 👍 

https://github.com/ms-jpq/coq_nvim/pull/185

**Comment by zeertzjq** [comment]
It's now become so much faster that it isn't even disabled.

**Comment by ms-jpq** [comment]
cool beans, thanks! :D
