### ISSUE TITLE
Enter in autocomplete isn't working properly

### ISSUE THREAD

**Issue by alessiocelentano** [ms-jpq/coq_nvim#205]
It seems there is a problem with the cursor position, the text isn't deleted and the completion is added before that text. Pressing space is an alternative.
Sorry if that's a duplicate or if I missed something.

https://user-images.githubusercontent.com/48618881/131842835-c0dcd434-6842-46b2-8bd4-ed134e34cdbe.mp4

**Comment by zeertzjq** [comment]
Try running `:imap <Enter>` and see what it is mapped to.

**Comment by zeertzjq** [comment]
If you are using `jiangmiao/auto-pairs` then this may be a duplicate of #34.

**Comment by alessiocelentano** [comment]
Yep, without auto-pairs it works. Thanks and sorry for the duplicate
