### ISSUE TITLE
:COQnow gives 'path\to\nvim\plugged\coq_nvim\win.bat' is not executable 

### ISSUE THREAD

**Issue by duydang2311** [ms-jpq/coq_nvim#206]
First of all, thank you for this plugin! After watching its features, I can't wait to try it out.
The issue happens to me while executing `:COQnow`:
`E5108: Error executing lua Vim:E475: Invalid value for argument cmd: 'C:\Users\Username\AppData\Local\nvim\plugged\coq_nvim/win.bat' is not executable`.

There seems to be no `win.bat` file at all, in my local path and on your repository as well.
Lastly, thank you for your time.

**Comment by ms-jpq** [comment]
sorry I made a typo, please update now.

**Comment by duydang2311** [comment]
It works flawlessly, thanks!
