### ISSUE TITLE
Ultisnips support

### ISSUE THREAD

**Issue by Mte90** [ms-jpq/coq_nvim#211]
I have some custom snippets but I don't see anything that explain how to add custom snippets.

To achieve this I am using https://github.com/SirVer/ultisnips but I can migrate to another solution compatible with this plugin.

**Comment by ms-jpq** [comment]
no custom snippet support yet.

i just added snippet repl like yesterday, and something else nice today (about 10 min ago), it will definitely show up when you do a `git pull` :D 

the full custom snippets will come probably before end of this weekend.

**Comment by Mte90** [comment]
Cool!

**Comment by ms-jpq** [comment]
WIP
https://github.com/ms-jpq/coq_nvim/pull/216/files

**Comment by ms-jpq** [comment]
almost there! here is a [preview of how it's gonna work](https://github.com/ms-jpq/coq_nvim/blob/dev/docs/SNIPS.md)

its taking much longer than expected

**Comment by ms-jpq** [comment]
![pic1](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/snip_load.gif)

![pic2](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/snip_parse.gif)

the only part left is to figure out why my hash function is unstable and a bit of recursive CTE work

**Comment by dnaaun** [comment]
> almost there! here is a preview of how it's gonna work

The gifs look amazing!

**Comment by ms-jpq** [comment]
i swear to god im gonna touch grass after this lol

**Comment by ms-jpq** [comment]
done, im gonna to touch grass now
