### ISSUE TITLE
RunTimeWarning coroutine was never awaited

### ISSUE THREAD

**Issue by Mte90** [ms-jpq/coq_nvim#212]
![Screenshot_20210903_110521](https://user-images.githubusercontent.com/403283/131980392-002adb6b-0462-4960-8899-0839028ebba3.png)

I got this error but I wasn't able to replicate but I thought that it was the case to report it :-)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/213
