### ISSUE TITLE
Path completion optimization

### ISSUE THREAD

**Issue by dppo** [ms-jpq/coq_nvim#214]
When a folder is selected, whether the completion of the selected folder can be automatically displayed

https://user-images.githubusercontent.com/85061291/132003596-aab07636-9143-4279-96f2-7f5343d68ae1.mov

**Comment by zeertzjq** [comment]
Try checking out #357. In #357 completion for content of completed directory is shown if you pressed `/` to accept completion.

**Comment by ms-jpq** [comment]
done thanks to @zeertzjq
