### ISSUE TITLE
error messages should either be into a log or on one line ( | COQ EXITED - 1)

### ISSUE THREAD

**Issue by Sumguy31** [ms-jpq/coq_nvim#219]
Installing COQ and running `COQnow` with failed requirements outputs:

>  ⛔️ python < 3.8.2
>     | COQ EXITED - 1

however since the command line inside of vim only shows one line by default, users may only see this:
>   | COQ EXITED - 1

which is really frustrating. And presumably other requirements may fail so it may not be obvious what is failing (a more human readable requirements list would also help). A better way would be to print this to a log, or to compress the error message to one line. which the user can view.

My work around is to redirect the output of the command line into a register and then pasting from the register into a buffer e.g.

`:redir @a`
` :COQnow`
` :redir END`

and then pasting into the buffer using  `"ap`

**Comment by zeertzjq** [comment]
Doesn't `:messages` show all of them?

**Comment by Sumguy31** [comment]
It does! didn't even know about the `:messages` command until now, thanks for the tip.  I guess it just caught me off guard since other messages (e.g. running `COQnow` without running `COQdeps` first) expands my message bar so the entire message is displayed

**Comment by ms-jpq** [comment]
humm I added a thing that pops everything out 

https://github.com/ms-jpq/coq_nvim/pull/216

its a in a mega PR though

**Comment by ms-jpq** [comment]
done
