### ISSUE TITLE
How to run COQnow on startup?

### ISSUE THREAD

**Issue by IndianBoy42** [ms-jpq/coq_nvim#22]
I don't really want to have to run COQnow everytime

I tried to run it in `init.lua` but its giving me an error that it is not an editor command

**Comment by npielawski** [comment]
`lua coq.COQnow()` seems to do the trick once the extension is loaded

**Comment by vxio** [comment]
This worked for me:

I created a new file `~/.config/nvim/after/plugin/coq.lua` and set 
```lua
vim.cmd('COQnow')

local lsp = require 'lspconfig'
lsp.gopls.setup(coq.lsp_ensure_capabilities({
  cmd = {"gopls", "serve"},
    settings = {
      gopls = {
        analyses = {
          unusedparams = true,
        },
        staticcheck = true,
      },
    },
}))
```

**Comment by gohm44** [comment]
I did try both of them but unfortunately still getting an error:

```E5108: Error executing lua [string ":lua"]:1: attempt to index global 'coq' (a nil value)```

I guess maybe is sill too early to execute command.
 I'm using packer as plugin manager. Does any of you use it?

**Comment by creativenull** [comment]
If you're using packer to lazy load `coq_nvim` then it won't work. You want to load it on demand, else `coq` variable won't be available, hence the error.

```
use {'ms-jpq/coq_nvim'}
```

**Comment by gohm44** [comment]
No, I'm not using packer to lazy load `coq_nvim`. 
```
use {'ms-jpq/coq_nvim'}
use {'ms-jpq/coq.artifacts'} 
```
I have noticed some issues in other threads related to packer, so my suspicions is packer-coq relation.
That's the reason of my question about it.

**Comment by Shougo** [comment]
You can use `autocmd VimEnter * COQnow`.

**Comment by ms-jpq** [comment]
@gohm44 

If you are using `packer`, the load order is a bit funny. 

Please update my repo and use the following config:

```lua
vim.schedule(function ()
  local lsp = require "lspconfig"
  require("packer").loader("coq_nvim coq.artifacts")
  lsp.<server>.setup(require("coq")().lsp_ensure_capabilities(<stuff...>))
end)
```

**Comment by ms-jpq** [comment]
Added a `--shut-up` flag.

`:COQnow --shut-up` will make `coq.nvim` not print the apple style greeting message in like 12 different languages.
