### ISSUE TITLE
When I press the <Space> to activate the selected snippets, it will add a space in the final

### ISSUE THREAD

**Issue by angryheng** [ms-jpq/coq_nvim#221]
![bug](https://user-images.githubusercontent.com/28853495/132197198-29c8420b-a048-47a8-bd7f-4b27a782b360.gif)

**Comment by zeertzjq** [comment]
You can use this mapping:

In Vimscript:
```vim
inoremap <silent><expr> <Space> complete_info(['selected']).selected != -1 ? "<C-Y>" : "<Space>"
```

In Lua:
```lua
vim.api.nvim_buf_set_keymap('i', '<Space>', [[complete_info(['selected']).selected != -1 ? "<C-Y>" : "<Space>"]], { expr = true, noremap = true, silent = true })
```

This also prevents appending a space when you press `<Space>` to insert a buffer word though.

**Comment by zeertzjq** [comment]
Actually `<Space>` is not a confirm key. The confirm key is `<C-Y>` (see `:h ins-completion-menu`).

**Comment by ms-jpq** [comment]
what @zeertzjq  said :)

**Comment by angryheng** [comment]
@zeertzjq Thanks!
