### ISSUE TITLE
Error starting python process when python is symlinked

### ISSUE THREAD

**Issue by GCBallesteros** [ms-jpq/coq_nvim#23]
I get the following error when running `:COQnow`

```
E5108: Error executing lua Vim:E475: Invalid value for argument cmd: '~/.pyenv/versions/neovim3/bin/python' is not executable
```

I specify the python interpreters used by nvim as follows:

```vim
let g:python3_host_prog='~/.pyenv/versions/neovim3/bin/python'
let g:python_host_prog='~/.pyenv/versions/neovim/bin/python'
```

Running `:checkhealth` confirms that (apparently) nvim is fine with my choice of Python interpreters. Just as a sanity check I confirmed that indeed the specified interpreters are executable

```bash
❯ ls -lh ~/.pyenv/versions/neovim3/bin/python
Permissions Size User     Date Modified Name
lrwxr-xr-x     9 garfield 24 Sep  2020  /Users/garfield/.pyenv/versions/neovim3/bin/python -> python3.8
```

Maybe it's the symlink?

Edit:
I tried to remove the `python_host_prog` so that I use the global Python interpreter and everything works then. So it looks like it's the symlink created by pyenv.

**Comment by heygarrett** [comment]
I'm running into the same issue. Commenting out the `python3_host_prog` in my init.vim also works for me as a temporary fix.

**Comment by tiagovla** [comment]
Same here.

**Comment by ms-jpq** [comment]
Please replace `python3_host_prog='~/...'` with `python3_host_prog=vim.env.HOME .. '/...'`

I am 95% sure what happened was that `~/` isnt being expanded to `$HOME`. Which the easiest way is for you to update like 5 characters

:D

**Comment by GCBallesteros** [comment]
Of course @ms-jpq was right. Expanding on her response the following fixed it for me on my `init.vim`.:

```vim
let g:python3_host_prog=$HOME .'/.pyenv/versions/neovim3/bin/python'
```
