### ISSUE TITLE
Feature request: do not enter placeholder name when expanding snippet marks

### ISSUE THREAD

**Issue by smjonas** [ms-jpq/coq_nvim#233]
When selecting a snippet that has marks we get a prompt saying ":pencil2:  Expand marks:". In a latex file I often type `sec`, then I select the snippet that expands to `\section`. This opens the prompt ":pencil2:  Expand marks:section name". Then I need to keep backspace pressed until I can type the actual section name that I want to insert.

I have never found a case where the preinserted text is text that I actually want to insert. So could there be an option (or even make this the default) to not show any text in the "expand marks" prompt? Thanks for this amazing plugin btw :)

**Comment by ms-jpq** [comment]
good point, will make that the default

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/235
