### ISSUE TITLE
Unexpected characters exist when trigger complete

### ISSUE THREAD

**Issue by letieu** [ms-jpq/coq_nvim#234]
I use nvim lsp for PHP, and when use <Space> key or <Enter> key to trigger complete, i have a character at after my cursor
![image](https://user-images.githubusercontent.com/53562817/132376176-48154079-2223-41b2-8e5f-63cc8dd94fce.png)

Here is error:
![image](https://user-images.githubusercontent.com/53562817/132376330-8da98969-ea2a-4e6a-8127-84f5ce3c91ee.png)
after press  Enter it look like this:
![image](https://user-images.githubusercontent.com/53562817/132376385-d353b4f3-dbec-4534-914a-696dc5727939.png)

or this if press Space key:
![image](https://user-images.githubusercontent.com/53562817/132376483-361eada4-4c90-437c-9b75-dee681f28eb9.png)

I face with this error only when use PHP  intelephense

**Comment by smjonas** [comment]
I had this issue as well today after updating. I fixed it by running `:COQdeps`, then restarting coq (`:COQnow`) and I think I also restarted Neovim afterwards. Maybe this will work for you😄

**Comment by ms-jpq** [comment]
sorry there was an old bug that did that, does this still happen on latest?

I cannot reproduce on a very tiny toy file

**Comment by ms-jpq** [comment]
in the recording, i pressed `k`, and it ended up where k is supposed to be

https://user-images.githubusercontent.com/50598611/132380336-0db591c2-1d27-4ef5-b809-98ccad9c48fc.mov
