### ISSUE TITLE
Snippets not working properly on Windows since the snippets change

### ISSUE THREAD

**Issue by TheLeoP** [ms-jpq/coq_nvim#236]
I have updated the plugin to the latest version, and run `:COQdeps` on both my Windows desktop computer and my Ubuntu Laptop. In Ubuntu everything works as expected, but on Windows I found a problem: the snippets aren't being expanded.
1. Open any file with snippets for that filetype (for example, my init.lua).
2. Write a snippets to let coq autocomplete it (for example, `if` ).
3. Select the snippet with <tab>.
4. Press <cr> (or the equivalent key) to trigger the completion.

The result is the autocompletion menu being closed and the message `Marks added: [-- body] [condition]` being printed, but the snippets doesn't expand.

Notes:
- As I said, this just happens on Windows, not on Ubuntu.
- This doesn't happen if I select any other thing on the step 2 (keyword, text, function, etc), just with snippets.

**Comment by ms-jpq** [comment]
... wtf, ok i am gonna get a windows VM up today. i pinky promise

**Comment by TheLeoP** [comment]
Thaaaanks. I guess giving support for both Windows and Linux could be a pain in the ass sometimes 😅

**Comment by ms-jpq** [comment]
i mean somebody asked me to add in support for openBSD, not even freeBSD, openBSD!, and apparently i had to change like 15 lines and it all worked.

windows is like, i dont even know what can go wrong since I don't have it anywhere except on my TV

**Comment by ms-jpq** [comment]
I couldn't get my tv box to output `ycbcr422` under linux, like at some point they ask you to compile the kernel with this random patch and like, just no.

**Comment by ms-jpq** [comment]
@TheLeoP can you help me with windows, I cant find `python` ... LOL

<img width="1009" alt="图片" src="https://user-images.githubusercontent.com/50598611/132395985-126c7541-04f5-4384-8fe0-7505cb19b78a.png">

---

I got this working like a year ago and forgot how to reproduce it, I have `C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps` in `%PATH%` already, which should mean that `nvim` can find it?

`!python` even works

**Comment by TheLeoP** [comment]
God, I hate Windows too. Maybe changing python for python.exe or something like that? Because that sounds like the script that checks if python is executable is giving the error, not Windows itself.

What happens if you type python on CMD or PowerShell?

**Comment by ms-jpq** [comment]
it works lol,

`echo jobstart(["python"])` doesnt work but `echo jobstart("python")` does.

---

from the docs:


```
		NOTE: on Windows if {cmd} is a List:
		  - cmd[0] must be an executable (not a "built-in"). If it is
		    in $PATH it can be called by name, without an extension: >
		      :call jobstart(['ping', 'neovim.io'])

```

so it should just work?

**Comment by TheLeoP** [comment]
It sounds like it should work. Maybe you found another bug ok Window, lol

**Comment by ms-jpq** [comment]
ok its a line ending issue,

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/239

please test it out :)

i hope thats the last of windows issue.

it was caused by `\r\n` being 1 longer than `\n`. the snippet PR tried to be consistent and make everything use `\n` but I missed a few update locations and never found out because I didn't test on windows

**Comment by TheLeoP** [comment]
Yes, it works. thaaaanks

**Comment by ms-jpq** [comment]
🙏
