### ISSUE TITLE
config-request: expose ability to map Select Next Item and Select Previous Item in completion menu 

### ISSUE THREAD

**Issue by vxio** [ms-jpq/coq_nvim#24]
In addition to `<tab>` and `<s-tab>` for selecting next/previous items in the completion menu, it'd be great to have this enabled for `<up>` and `<down>` arrows.

**Comment by mcauley-penney** [comment]
If your config is in Lua or you use Lua at all, these are currently working for me

```Lua
local send_keys = function(str)
    return vim.api.nvim_replace_termcodes( str, true, true, true )
end

_G.arrow_down = function()
    return vim.fn.pumvisible() == 1 and send_keys "<C-n>" or send_keys "<down>"
end


_G.arrow_up = function()
    return vim.fn.pumvisible() == 1 and send_keys "<C-p>" or send_keys "<up>"
end 

map( 'i', '<up>',   'v:lua.arrow_up()',   { expr = true, silent = true }  )
map( 'i', '<down>', 'v:lua.arrow_down()', { expr = true, silent = true }  )
```

**Comment by ms-jpq** [comment]
wait it already *works on my machine*™,

does it actually not work for you guys to scroll up and down with `<up>` and `<down>`?

**Comment by ms-jpq** [comment]
that is freaking weird

**Comment by zeertzjq** [comment]
~~These two seem to work without any mappings. If you already have these two mapped to something else then they will not work.~~
`<Up>` and `<Down>` are actually different from `<C-P>` and `<C-N>`. @McAuleyPenney was right.

**Comment by ms-jpq** [comment]
what @zeertzjq said
