### ISSUE TITLE
How to have snippets shown first in the completion menu?

### ISSUE THREAD

**Issue by qazip** [ms-jpq/coq_nvim#241]
I was using nvim-compe and I am "test driving" coq. I need to have snippets shown first in the completion menu. Is there a way to set priority?

**Comment by qazip** [comment]
It seems like snippets are already first. No idea what I changed to make this happen. Oh well..

**Comment by dnaaun** [comment]
This information is available in the documentation [here](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SOURCES.md#coq_settingsclientsxweight_adjust), please try to read through before asking next time.

Like you, I like my snippets to be ranked the highest, and the following settings work great for me:

```lua
vim.g.coq_settings = {
   -- Other settings
  clients = {
    buffers = {
      enabled = true,
      weight_adjust = -1.9,
    },
    tree_sitter = {
      enabled = true,
      weight_adjust = -1.5
    },
    lsp = {
      enabled = true,
      weight_adjust = 1.5
    },
    snippets = {
      enabled = true,
      weight_adjust = 1.9
    },

  }
}
```
Note the above is lua code, so if you're configuring with vimscript, you'll have to change the syntax.

**Comment by qazip** [comment]
I had tried that before but it is not working LSP still shows up first.. May be something with my config. I'll try to figure it out. Thanks though!

**Comment by ioreshnikov** [comment]
I have a similar problem with ordering (I want BUF suggestions to be at the very bottom) and no matter what I do, I cannot force it. I have tried the following weights

```
vim.g.coq_settings = {
    auto_start = 'shut-up',
    display = {
        pum = {
            fast_close = false
        }
    },
    clients = {
        lsp = {
            enabled = true,
            weight_adjust = 1.50
        },
        snippets = {
            enabled = true,
            weight_adjust = 1.25
        },
        tree_sitter = {
            enabled = true,
            weight_adjust = 1.00
        },
        buffers = {
            enabled = true,
            weight_adjust = -2.00,  -- doesn't help that much
        },
    }
}
```

but it didn't help. I think the matching and ordering algorithm might be too smart for it's own good. I would prefer if there was an option to do a hierarchical ordering: first order the sources in a deterministic manner (strictly by the weight, for example) and then a whatever-we-do-magic inside each source. @ms-jpq do you think it's possible to have an optional behaviour like this?

As of now, I simply have to disable BUF source at all.
