### ISSUE TITLE
LSP autocompletion doesn't load

### ISSUE THREAD

**Issue by rywng** [ms-jpq/coq_nvim#243]
### Hello, dev. 
Thanks for your awesome plugin, everything works super well, including snippets, Treesitter and T9. but my completion with lsp doesn't seem to work. I followed every other issues about lsp and packer and their methods, also read through all the docs, but LSP just doesn't work properly.

#### Here's what I get using   :LspInfo
```
 
 Language client log: /home/***/lsp.log
 Detected filetype:   c
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: c
 
 Config: cpp
 	filetypes:         c, cpp, objc, objcpp
 	root directory:    /home/***/nvim
 	cmd:               /home/***/.local/share/nvim/lspinstall/cpp/./clangd/bin/clangd --background-index
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: lua, cpp, python, bash
```
#### here's my config in packer.nvim
``` lua
    use {'neovim/nvim-lspconfig', event = 'BufRead'}
    use {
        'kabouzeid/nvim-lspinstall',
        after = 'nvim-lspconfig',
        config = function() require "plugins.lspinstall" end
    }
    use {
        'ms-jpq/coq_nvim',
        branch = 'coq',
        requires = {'ms-jpq/coq.artifacts', branch = 'artifacts'}
    }
```
#### and in plugins/lspinstall.lua:
``` lua
local function setup_servers()
    require'lspinstall'.setup()
    local servers = require'lspinstall'.installed_servers()
    for _, server in pairs(servers) do
        require'lspconfig'[server].setup(
            coq.lsp_ensure_capabilities({capabilities = capabilities}))
    end
end

-- Automatically reload after `:LspInstall <server>` so we don't have to restart neovim
require'lspinstall'.post_install_hook = function()
    setup_servers() -- reload installed servers
    vim.cmd("bufdo e") -- this triggers the FileType autocmd that starts the server
end

-- setup coq.lua
local lsp = require 'lspconfig'
require("packer").loader("coq_nvim coq.artifacts")
vim.g.coq_settings = {auto_start = true, clients = {tabnine = {enabled = true}}}
local coq = require 'coq'
setup_servers()

-- run coq.lua
vim.cmd("COQnow -s")
```
I think the problem might be coq unable to attatch to the LSP server, and I'm new to nvim and lua, any help will be appreciated, 
### Thanks!!

**Comment by dnaaun** [comment]
The output of `:LspInfo` is showing that no LSPs are actually active when you're in the file. So this is definitely not a `coq_nvim` issue. If the LSP was active, the output should say `1 client(s) attached to this buffer`.  (The number can be more than 1 if you installed more than 1 LSP for the filetype).

Unfortunately, I'm not a user of the `lspinstall` plugin, so I'm not sure what's wrong with your setup. Your best bet would be to ask in the `lspinstall` repo.

**Comment by rywng** [comment]
Thanks for your help. Very appreciated ❤️

**Comment by ms-jpq** [comment]
haha u have a funny profile picture!
