### ISSUE TITLE
Even when multiple LSPs are attached coq doesn't pick them up.

### ISSUE THREAD

**Issue by samrathchadha** [ms-jpq/coq_nvim#244]

**Comment by ms-jpq** [comment]
is it tailwind?

I added a debug option to print out which LSP servers respond

https://github.com/ms-jpq/coq_nvim/pull/246

```sh
COQ_DEBUG=1 nvim index.html
```

the logs start with `LSP !!`,

for whatever reason tailwind sever is returning zero results

**Comment by ms-jpq** [comment]
![图片](https://user-images.githubusercontent.com/50598611/132562601-9ad879f0-be5c-4e01-8ff1-187e28ac7fb0.png)

oops im dumb, i guess ill debug more

**Comment by ms-jpq** [comment]
![图片](https://user-images.githubusercontent.com/50598611/132563223-caecf173-c0e7-4b4d-b493-aa68f60f1103.png)

i tested it and seems to work with `pyright` and `pylsp` no issue, can you post the LSPs that dont work for you?

**Comment by samrathchadha** [comment]
Sure its,
tailwindcss and typescript
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/69572668/132616409-410246fe-c667-4535-b0f5-b562940b3cfd.png">

**Comment by samrathchadha** [comment]
Hey @ms-jpq it still doesn't work

**Comment by dnaaun** [comment]
Hey @samrath2007 , tsserver works successfuly for me with coq. What is curious, is that the output of `:LspInfo` for you says "typescript" as the name of the client, but for me, it says "tsserver". Indeed, when I look here, https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md, the name of the LSP for typescript in neovim lsp-config is tsserver. Would you happen to know why that might be the case? I'm not sure if this is related to your problem, but I thought it was worth investigating.

Also, is it that `coq` doesn't pick up on _any_ LSP that you install, or just typescript and tailwind? Could you perhaps try installing pyright(`npm install -g pyright`), and then opening a python file (like `some_file.py`), and check if you see completions if you type "import ")?

**Comment by samrathchadha** [comment]
TSSSERVER works for me alone and so does pyright

**Comment by ms-jpq** [comment]
does tailwindcss work with the built-in LSP omnifunc for you?

**Comment by ms-jpq** [comment]
like on a markdown file or something, so you know only 1 LSP is active.

**Comment by samrathchadha** [comment]
It doesn't

**Comment by ms-jpq** [comment]
then it seems like there is something wrong with `tailwindcss`, because if its the only language server, and the nvim's builtin lsp's completion func also doesn't return anything, its unlikely that both the nvim butlin and coq are both wrong.

**Comment by samrathchadha** [comment]
I guess so, I'll raise an issue there, thanks!
