### ISSUE TITLE
Regex on snippet not recognized

### ISSUE THREAD

**Issue by JoseConseco** [ms-jpq/coq_nvim#247]
Now I know  regex  works for:  ${TM_FILEPATH/(.*)/${1:/upcase}/}

But it wont work for very similar example (I want to upcase mirrored $1 tabstop) :
```vim
snippet test
	${1} = output: ${1/(.*)/${1:/upcase}/}
```
It errors about  `/` after second $1 in code above.  
![image](https://user-images.githubusercontent.com/13521338/132568148-52846106-f9ae-4c0a-b8a6-24cb809fcdf9.png)

**Comment by ms-jpq** [comment]
correct me if im wrong, thats not in the [LSP specs](https://github.com/microsoft/language-server-protocol/blob/main/snippetSyntax.md) right?

**Comment by ms-jpq** [comment]
![图片](https://user-images.githubusercontent.com/50598611/132570262-e9eb0a04-6080-4846-bda6-d58e9bcf7f7e.png)

`$1` is not `[_a-zA-Z] [_a-zA-Z0-9]*`

**Comment by JoseConseco** [comment]
I'm not sure If I understand  but in TM_FILEPATH case the variable is :   
 - TM_FILEPATH and it is  regexed by (.*) correctly, 
-  second case  is exactly the same except the variable changed from TM_FILEPATH  to   value of  $1    (it should not be parsed literally as '1' )  
The syntax of not working snippet is taken from VS code (where it is parsed correctly) , so I assume it is correct.

**Comment by ms-jpq** [comment]
here is the section for variables:

---


### Variables

With `$name` or `${name:default}` you can insert the value of a variable. When a variable isn’t set, its *default* or the empty string is inserted. When a variable is unknown (that is, its name isn’t defined) the name of the variable is inserted and it is transformed into a placeholder.

The following variables can be used:

* `TM_SELECTED_TEXT` The currently selected text or the empty string
* `TM_CURRENT_LINE` The contents of the current line
* `TM_CURRENT_WORD` The contents of the word under cursor or the empty string
* `TM_LINE_INDEX` The zero-index based line number
* `TM_LINE_NUMBER` The one-index based line number
* `TM_FILENAME` The filename of the current document
* `TM_FILENAME_BASE` The filename of the current document without its extensions
* `TM_DIRECTORY` The directory of the current document
* `TM_FILEPATH` The full file path of the current document


---


so I think I got it? unless I read it wrong, you cant substitute a variable with a link right?

I could be wrong though

**Comment by JoseConseco** [comment]
Well IMO it would be more flexible if you could regex  format tabstops.  I'm not sure if Ultisnips follows LSP specs but from their docs:
> A transformation has the following syntax: >
>    ${<tab_stop_no/regular_expression/replacement/options}

Anyway you coq plug is great and from my test gives more relevant suggestions than cmp. I will have to live with manually converting tabs  :cry:   Thx for your time

**Comment by ms-jpq** [comment]
yeah sorry, unfortunately i do not have the bandwidth to build a superset of LSP grammar.

**Comment by ms-jpq** [comment]
vacode uses a superset of the LSP grammar, i checked their release notes
