### ISSUE TITLE
Integration with a snippet source

### ISSUE THREAD

**Issue by ghost** [ms-jpq/coq_nvim#257]
~~The title explains this issue, I think it would be nice to add a source for a snippet engine like `vim-vsnip` to have better snippet integration (expand snippet with `tab`, jump to placeholder with `tab`) so it delivers the same experience as other completion panels like `nvim-cmp`~~

Update: removed the first part of this because of #145, where ms-jpg explained why he will not add support for other snippets engines.

If the integration is *not possible*, the other solution would be to add support for snippet banks like `friendly-snippets`, and be able to jump to snippet placeholders by using the `tab` key.

**Comment by ms-jpq** [comment]
i dont have enough bandwidth for this.

coq is already huge.

**Comment by ms-jpq** [comment]
sorry

**Comment by ms-jpq** [comment]
oh adding support for community snips is easy!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/259

will be part of this PR, for the friendly snips 👍

**Comment by ghost** [comment]
> i dont have enough bandwidth for this.
> 
> coq is already huge.

Yeah, that's why I removed the first part for vim-vsnip (and `luasnip`, `snippets.nvim`...) because of the mentionned issue that I read.

And thanks for the PR!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq.artifacts/pull/10
its been compiled into the snippets,
