### ISSUE TITLE
Integration with Vimtex

### ISSUE THREAD

**Issue by krillin666** [ms-jpq/coq_nvim#258]
First of all, thanks for the work done on this beautiful project.

I rely heavily on [Vimtex](https://github.com/lervag/vimtex) for my academic writing and used it along Deoplete.
Vimtex supports a lot of autocomplete plugins and has documentation for those, but coq is missing.

Do you know of a way of integrating the autocompletion of Vimtex into coq ?

Thank you !

**Comment by dnaaun** [comment]
Hey @krillin666 , I'm a vimtex user too. For completion, it provides an `omnifunc`, which coq doesn't support as a source. What I did was that I installed [texlab](https://github.com/latex-lsp/texlab), a latex LSP, which gave me autocompletion. It actually supports continous compiling and synctex as well, but I've been too lazy to fully convert over, and I just use texlab for completion, and vimtex for continous compiling. 

Let me know if you have any questions.

**Comment by ms-jpq** [comment]
yeah im thinking about how to integrate third party completion sources,

the issue is that as soon as you start support a single third party client, your code base starts to ossify, since you will be necessarily be exposing some of the internals to third parties.

in order to limit the ossification, you have to build solid abstractions first, and while I think `coq.nvim`  has pretty good internals, i will still need to put much more design work into this.

what i absolutely do not want is to get into a situation where everything is so ossified that a clean break has to occur for any more potential improvements .

**Comment by ms-jpq** [comment]
so the status on this is, its gonna come eventually, but i make zero promises on when

**Comment by dnaaun** [comment]
@krillin666 , it looks like your best bet is to install texlab like I suggested.

**Comment by ms-jpq** [comment]
i have some ideas of how i would implement the shim layer though :) i slept on it and it will come after next week i think (im busy entire week next week)

**Comment by ms-jpq** [comment]
basically the shim layer will re-use the LSP parser, that way no internals are exposed

**Comment by ms-jpq** [comment]
and all the sources get stuff like caching, etc for free

**Comment by krillin666** [comment]
@davidatbu Thank you for the temporary workaround !
@ms-jpq Thank you for your answer and the for considering adding support for Vimtex (or Omnifunctions). I really do want to use nvim-coq so I'll wait till the integration is possible, best of luck !

**Comment by ms-jpq** [comment]
WIP

https://github.com/ms-jpq/coq_nvim/pull/261

**Comment by krillin666** [comment]
> WIP
> 
> #261

You are insane ! I'm sure you're going to figure it out. I just spent a whole day trying to find a replacement autocompletion plugin which worked with Omnifunction and Ultisnips but none were worth it.

**Comment by ms-jpq** [comment]
don't get your hopes up  :p,

its not gonna get all done for 2-3 days, because I also need to write the third party integration from `vimtex` -> `coq` on top of making `coq` accept third party plugins.

and its actually sunny today , so im gonna touch some grass first :D

**Comment by ms-jpq** [comment]
but yeah the final sources thingy will be very simple to write:

https://github.com/ms-jpq/coq_nvim/blob/dev/docs/CUSTOM_SOURCES.md

**Comment by krillin666** [comment]
> don't get your hopes up :p,
> 
> its not gonna get all done for 2-3 days, because I also need to write the third party integration from `vimtex` -> `coq` on top of making `coq` accept third party plugins.
> 
> and its actually sunny today , so im gonna touch some grass first :D

Please do take the necessary time to maintain the code core integrity, but above all to have time to enjoy life 😄

**Comment by ms-jpq** [comment]
@krillin666 
![图片](https://user-images.githubusercontent.com/50598611/133147167-b53f0885-a692-4713-a950-f2e53b3c2f56.png)


I will use this for a day or so and see if everything is good, after that ill merge it

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/blob/coq/docs/CUSTOM_SOURCES.md

done,

its **even faster** than just using `vimtex`, `orgmode`, etc, because `coq` transparently  adds a layer of `sqlite` cache
