### ISSUE TITLE
Initial setup guide

### ISSUE THREAD

**Issue by Trid-collab** [ms-jpq/coq_nvim#278]
I am new to this. I have been using nvim.cmp and want to try out something which can run out of box like say coc without much tinkering and be fast on say pyright and others 
I was given to understand that this can do this. I tried installing it but couldn't get it working properly. I feel that I am missing something. Could you direct me to some initial setup guide which could enable a noob like start using this.

**Comment by dnaaun** [comment]
Hey @Trid-collab, the [Install section](https://github.com/ms-jpq/coq_nvim#install) on the README should 
be enough to get started. I've reproduced it below:

```vim
" main one
Plug 'ms-jpq/coq_nvim', {'branch': 'coq'}
" 9000+ Snippets
Plug 'ms-jpq/coq.artifacts', {'branch': 'artifacts'}

" Third party sources -- See https://github.com/ms-jpq/coq.thirdparty
Plug 'ms-jpq/coq.thirdparty', {'branch': '3p'}
```


Right below that on the README, it says that to start coq, one must run `:COQnow`. Have you followed these stepsand still get no auto completion?

I do agree that the README could be more straightforward in allowing one to get started as quickly as possible. I might submit a PR to suggest what I think it should look like, but the maintainer is busy this week so that would have to wait.

**Comment by Trid-collab** [comment]
Hi @davidatbu, thank you. I have tried that. Its not issue of not getting the autocomplete, but the more of getting it to work smoothly and with the speed the site mentions. I guess I was missing configs which I need to put in to work with lspconfig and and lspinstall. Coming from vs code I was wondering how could I get hover documents and auto signature always on.  I tried and then went back to cmp again. I would like to coq again.

**Comment by dnaaun** [comment]
If `nvim-cmp` works well for you, that's great, and it may be a good idea to close this issue. But if you want to get coq working, I'm still not exactly sure what you are having issues with. You say `coq` is not working "smoothly and quickly". Can you be more specific (or provide screenshots perhaps)?

Regarding having "hover documents and auto signature always on". `coq` doesn't display the function signature when you type the arguments. To get that working you would need to install `lsp_signature`. Have a look at their [Github page](https://github.com/ray-x/lsp_signature.nvim) for how to get that working. It may be that `nvim-cmp` provides this functionality itself, I am not sure.

Regarding hover documentation, you actually do *not* need to install either `coq` or `nvim-cmp`. Neovim provides this functionality by itself when you get an LSP working. If you have followed the instructions for `nvim-lspconfig`, in particular,  [the section about keybindings](https://github.com/neovim/nvim-lspconfig#keybindings-and-completion), you should be able to press "K" in normal mode and get hover documentation for any symbol/word. Like the following:


<img width="695" alt="Screen Shot 2021-09-17 at 10 58 59 AM" src="https://user-images.githubusercontent.com/52462475/133747761-aee7affb-7c40-44ea-b60e-d482dfdd1915.png">

Let me know if I was unclear. You're new to the vim/neovim world, so feel free to ask questions.

**Comment by ms-jpq** [comment]
related, but i am building a two way bridge between `coq.nvim`'s lua sources and `nvim-cmp`'s lua sources.

👍

**Comment by dnaaun** [comment]
Hope you touch grass this weekend @ms-jpq 😆

**Comment by Trid-collab** [comment]
Thank you for your support. Let me try it out setting it up once again,
