### ISSUE TITLE
Occasional type mismatch in coq.lsp.types.Command.arguments

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#283]
When editing a Lua file, `coq.lsp.types.Command.arguments` is occasionally a `list` of `dict`s instead of a string, producing a lot of error messages. (In all error messages `title` is `autoRequire`.)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/commit/d9504a7619f5828f32cfd34fe50b55a8dbd9c34b

thanks for finding it!
