### ISSUE TITLE
Empty clients.snippets.warn array doesn't suppress warning

### ISSUE THREAD

**Issue by bkesby** [ms-jpq/coq_nvim#287]
Thank you very much for your work, this really is the fastest completion engine I've come across :+1: 

Attempting to suppress the `No compatible snippets found` warning whilst lazy loading coq.artifacts unitl "InsertEnter" using packer. The following function is run before loading coq and the auto_start function works however clients.snippets.warn doesn't.

```lua
-- lua/plugins/configs/coq.lua
M.setup = function()
   vim.g.coq_settings = {
      auto_start = "shut-up",
      clients = {
         snippets = {
            warn = {},
         },
      },
}
end
```

Any suggestions? I imagine an empty lua array is not being registered the same as in vimscript?

packer use:
```lua
-- lua/plugins/init.lua
use {
   "ms-jpq/coq-nvim",
   branch = "coq",
   event = "VimEnter",
   setup = function()
      require("plugins.configs.coq").setup()
   end,
}
```

**Comment by ms-jpq** [comment]
LOL, how did i miss this, I only added an option to configure warn outdated, but forgot to add a toggle for warn missing.

guess since I always had snippets installed I never realized !

**Comment by bkesby** [comment]
Glad I could help spot it for you

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/290
