### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by quangIO** [ms-jpq/coq_nvim#298]
I am trying to use coq_nvim with rack_langserver and hls. While hls + coq_nvim works just fine, I run into the following error when typing Racket code. 
```lua
Error executing vim.schedule lua callback: ...pack/packer/opt/lsp_signature.nvim
/lua/lsp_signature.lua:166: bad argument #1 to 'gsub' (string expected, got tabl
e)
```
My config looks like this.
```lua
local lsp = require "lspconfig"
local coq = require "coq"

lsp.racket_langserver.setup{}
lsp.hls.setup{}
lsp.racket_langserver.setup(coq{}.lsp_ensure_capabilities{})
lsp.hls.setup(coq{}.lsp_ensure_capabilities{})
```

I am using doom-nvim with neovim v0.5.0 on MacOS. 

Related issue: https://github.com/ms-jpq/coq_nvim/issues/222

**Comment by zeertzjq** [comment]
Inferring from the error messages, you should report this issue to [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim). I doubt you are not using the latest version of that plugin though.

**Comment by ms-jpq** [comment]
yeah what @zeertzjq  said,

thanks pal!
