### ISSUE TITLE
in arch linux there is no python3-venv package

### ISSUE THREAD

**Issue by CRAG666** [ms-jpq/coq_nvim#299]
I can't find this package on arch linux, even when I install virtualenv the error still persists.

**Comment by zeertzjq** [comment]
What error? `venv` module comes with `python` package. What does `python -m venv --help` output?

**Comment by CRAG666** [comment]
this is error, `Please install python3-venv separately. (apt, yum, apk, etc) `

**Comment by zeertzjq** [comment]
What does `python -m venv --help` output?

**Comment by CRAG666** [comment]
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps] ENV_DIR [ENV_DIR ...]

Creates virtual Python environments in one or more target directories.

positional arguments:
  ENV_DIR               A directory to create the environment in.

optional arguments:
  -h, --help            show this help message and exit
  --system-site-packages
                        Give the virtual environment access to the system site-packages dir.
  --symlinks            Try to use symlinks rather than copies, when symlinks are not the default for the platform.
  --copies              Try to use copies rather than symlinks, even when symlinks are the default for the platform.
  --clear               Delete the contents of the environment directory if it already exists, before environment creation.
  --upgrade             Upgrade the environment directory to use this version of Python, assuming Python has been upgraded in-place.
  --without-pip         Skips installing or upgrading pip in the virtual environment (pip is bootstrapped by default)
  --prompt PROMPT       Provides an alternative prompt prefix for this environment.
  --upgrade-deps        Upgrade core dependencies: pip setuptools to the latest version in PyPI

Once an environment has been created, you may wish to activate it, e.g. by sourcing an activate script in its bin directory.

**Comment by zeertzjq** [comment]
So it is clear that you already have `venv`, but `coq` somehow failed to create a virtual environment.

**Comment by CRAG666** [comment]
that seems to be the problem, do you know any solution?

**Comment by zeertzjq** [comment]
Does adding `vim.g.python3_host_prog = '/usr/bin/python3'` to your Neovim config help?

**Comment by CRAG666** [comment]
the error persists

**Comment by zeertzjq** [comment]
A method that may help you debug the problem (assuming you used `packer` to install `coq`):
- Edit `~/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/__main__.py` or `~/.local/share/nvim/site/pack/packer/opt/coq_nvim/coq/__main__.py`: change line 77 from `exit(1)` to `raise`
- Open Neovim, run `:COQdeps`, and see what the full error messages are (keep pressing Enter until all the error messages are shown)

**Comment by CRAG666** [comment]
https://stackoverflow.com/questions/44967202/pip-is-showing-error-lsb-release-a-returned-non-zero-exit-status-1/44967506
After following up on the error, he solves it by deleting a file that had nothing to do with his project, an apology
