### ISSUE TITLE
How do I define custom snippets for any filetype?

### ISSUE THREAD

**Issue by dkasak** [ms-jpq/coq_nvim#304]
Maybe I'm missing something, but how do I define user snippets which are available in any filetype? I tried adding `_.snip` to `~/.config/nvim/coq-user-snippets` (and recompiling snippets) but that did nothing.

**Comment by ms-jpq** [comment]
right now you can't

i should add it

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/330

**Comment by dkasak** [comment]
Thanks a lot for adding this!
