### ISSUE TITLE
Does not properly handle LSP snippets that should replace previous characters

### ISSUE THREAD

**Issue by IndianBoy42** [ms-jpq/coq_nvim#31]
For example with rust-analyzer, we have snippets like:
```
variable.dbg<CR>
```
Becomes
```
dbg!(variable)
```
This worked with `nvim-compe` but with `coq_nvim` it instead becomes:
```
variable.dbg!(variable)
```

i have `coq.lsp_ensure_capabilities` on the rust server setup.

**Comment by ms-jpq** [comment]
hummm,  i have rust-analyzer too, I will look into this, they probably included an edit range to the snippets, which I was not expecting, but should be pretty simple fix.

good catch!

**Comment by kinbiko** [comment]
Heads up that I'm also seeing this with Go too:

![image](https://user-images.githubusercontent.com/8797880/130073781-e3ffe093-8c44-4361-afcf-69a622ea9f77.png)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/148

coming

**Comment by ms-jpq** [comment]
done
