### ISSUE TITLE
Expanding completion which ends in ) immediately left of ) results in a single ) instead of ))

### ISSUE THREAD

**Issue by joiharalds** [ms-jpq/coq_nvim#311]
Using `r_language_server` so I don't know whether it might be related to the upstream issue mentioned in #303.

When a completion ending in ) is expanded to the left of ) which should result in )) only results in ) so a parenthesis is missing.

This is bad because it is common to expand two function completions in a row like
`mean(as.numeric())` but the expansions now give `mean(as.numeric()`

This happens with a minimal `init.vim` which only loads `coq` and `lspconfig`.

**Comment by zeertzjq** [comment]
1. What key did you press to accept the completion?
2. Does it work normally when there is no `)` after cursor?

**Comment by joiharalds** [comment]
1. \<CR> and I have not changed the default keymap in any way
2. Yes, picking the LSP completion for `as.numeric` I did this test
![Screenshot from 2021-09-23 10-35-25](https://user-images.githubusercontent.com/14778057/134493077-fd840a7a-aad0-45c4-ad29-62692e2de75c.png)
not shown is `as.numeric()` without any trailing symbol which also works.

**Comment by zeertzjq** [comment]
Maybe this bug is related to fuzzy completion then. Possibly related: #250.

**Comment by ms-jpq** [comment]
yeah @zeertzjq is right, iwill fix after work.

i tried to make coq be too smort and it backfired

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/315
