### ISSUE TITLE
[Bug] Python modules do not show autocompletion after the period

### ISSUE THREAD

**Issue by PlatyPew** [ms-jpq/coq_nvim#319]
There's an issue with autocompletion for Python modules where the LSP suggestions do not kick in until I've typed in the first letter.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/23520617/135003319-d409d1df-e299-41e7-990f-88ba21faca8d.gif)

Here's my configuration:
```lua
vim.g.coq_settings = {
    auto_start = 'shut-up',
    clients = {
        tabnine = {
            enabled = false,
        },
    },
    keymap = {
        recommended = false,
    },
}

local lspconfig = require'lspconfig'
local coq = require'coq'

lspconfig.jedi_language_server.setup(coq.lsp_ensure_capabilities{
    cmd = { "jedi-language-server" },
    flags = { debounce_text_changes = 500 },
})
```

**Comment by ms-jpq** [comment]
i tried it, the issue is that `os` in python is such a big namespace, it should return a big list of results and LSP client is too slow to calculate all the results in `88ms`.

**Comment by ms-jpq** [comment]
You can either change the defaults so that coq waits longer or use manual completion.

**Comment by Monirzadeh** [comment]
i have same issue with any module.
should i set any specific setting in config?
it just show me `self.` noting else
```
require'lspconfig'.pyright.setup{}

local lsp = require "lspconfig"
local coq = require "coq" -- add this
lsp.pyright.setup(coq.lsp_ensure_capabilities{})
```

**Comment by h0wser** [comment]
I also have this issue, it is not due to timeouts. I put my timeout to 0.5s, still same behavior. According to COQstats LSP avg duration is less than 70ms.
