### ISSUE TITLE
jump_to_mark is broken

### ISSUE THREAD

**Issue by joiharalds** [ms-jpq/coq_nvim#321]
1. Using default jump_to_mark key <c-h> the behavior is weird
![Screenshot from 2021-09-28 19-24-19](https://user-images.githubusercontent.com/14778057/135152852-bed7bb75-f7f9-4c26-90be-bf06aa4f4547.png)
![Screenshot from 2021-09-28 19-24-24](https://user-images.githubusercontent.com/14778057/135152851-a5d393f1-78bc-4574-9826-49b79806d3ca.png)
![Screenshot from 2021-09-28 19-24-35](https://user-images.githubusercontent.com/14778057/135152848-7e9a2a0e-057b-4e0c-9dcc-237e036ddb7e.png)

and I don't know whether it's the snippets fault or jump_to_mark behavior that the `end{}` is empty instead of containing `document`

2. Setting jump_to_mark to different key than default i.e. `<c-,>` doesn't work

Minimal init.vim
```
call plug#begin(stdpath('data').'/plugged')

Plug 'ms-jpq/coq_nvim', {'branch': 'coq'}

Plug 'ms-jpq/coq.artifacts', {'branch': 'artifacts'}
Plug 'ms-jpq/coq.thirdparty', {'branch': '3p'}

call plug#end()

lua require("coq")
```

**Comment by zeertzjq** [comment]
1. Did you type `document` in the `Expand marks ["env", ""]:` prompt?
2. You cannot use `<c-,>` in a terminal emulator. Try something else like `<c-q>` or `<c-j>`.

**Comment by joiharalds** [comment]
Thanks for the clarification. Mapping to `<c-f>` works and I haven't seen snippets that work like this before so my bad.
