### ISSUE TITLE
Doubt `jump_to_mark`

### ISSUE THREAD

**Issue by martinsrso** [ms-jpq/coq_nvim#325]
I wonder if I would like to get to reverse the 'jump_to_mark` in snippet? Because it always comes with content as first. Follow the example.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/11994788/135474328-6bffb955-be35-49e0-b4d4-137778f82938.png">

**Comment by ms-jpq** [comment]
hummm, like thats a snippet's issue imo, they decide were the `$0`, `$1`, `$2` markers are located, but it's pretty easy to do

**Comment by martinsrso** [comment]
Would you like to put as an option in settings?

**Comment by majjejjam** [comment]
I think the problem is that other snippet engines use another order: they start with `$1`, `$2`, …, `$n` and always end with `$0`. The issue occurs because the snippets provided by `coq` are sourced from places intended for use with this other order.

**Comment by ms-jpq** [comment]
what? isnt `$0` the cursor location?

> With tab stops, you can make the editor cursor move inside a snippet. Use $1, $2 to specify cursor locations. The number is the order in which tab stops will be visited, whereas $0 denotes the final cursor position. Multiple tab stops are linked and updated in sync.


so why would `$0` come after all the other jump marks, are vim snips different or something

**Comment by ms-jpq** [comment]
<img width="591" alt="图片" src="https://user-images.githubusercontent.com/50598611/135681670-6a04996c-62b3-4ecd-981b-7cbe0dd9fefd.png">


wait they are actually the opposite.

lol, ok will fix

**Comment by zeertzjq** [comment]
Actually LSP specification also says this:
```
With tabstops, you can make the editor cursor move inside a snippet. Use $1, $2 to specify cursor locations. The number is the order in which tabstops will be visited, whereas $0 denotes the final cursor position. Multiple tabstops are linked and updated in sync.
```

**Comment by zeertzjq** [comment]
> what? isnt `$0` the cursor location?
> 
> > With tab stops, you can make the editor cursor move inside a snippet. Use $1, $2 to specify cursor locations. The number is the order in which tab stops will be visited, whereas $0 denotes the final cursor position. Multiple tab stops are linked and updated in sync.
> 
> so why would `$0` come after all the other jump marks, are vim snips different or something

Doesn't it say "**final** cursor position"? So `$0` should always come after all the other jump marks. They are the same.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/329

fixed
