### ISSUE TITLE
E15 pumvisible() error with Telescope

### ISSUE THREAD

**Issue by djensenius** [ms-jpq/coq_nvim#332]
If I open a Telescope window, and hit escape I get the following error:

E15: Invalid expression: pumvisible() ? '^E' : '^R=<80><fd>R59_FlushBuffer()^Mpmuvisible() ? '^E[' : '^[''

Any ideas what the problem might be?

**Comment by ms-jpq** [comment]
no idea, but coq does not have anything called flush buffer.

**Comment by zeertzjq** [comment]
Telescope doesn't have anything called `FlushBuffer` either, so it is possible that some other plugin is interfering.

**Comment by ms-jpq** [comment]
yeah i will just close this, it doesnt seem related

**Comment by djensenius** [comment]
Ahh, I tracked it down. It was an older autoclose plugin. Sorry for the mixup!
