### ISSUE TITLE
request: only fetch and show preview documentation popup after a certain time

### ISSUE THREAD

**Issue by vxio** [ms-jpq/coq_nvim#345]
Could we add an option to only show the preview documentation popup after a certain amount of time? 
Without this option, there's a small delay as we quickly tab through the autocomplete suggestions because it's fetching the preview data.

Jetbrains IDEs have this nice option:
<img width="443" alt="CleanShot 2021-10-10 at 10 35 15@2x" src="https://user-images.githubusercontent.com/29054071/136706981-cb0eed60-a234-440c-be5c-6a4b1ee23b4c.png">

**Comment by ms-jpq** [comment]
wait so you want the small delay to be longer? i mean sure? i can probably add that in.

**Comment by vxio** [comment]
An option to set the delay would be great because there's a stutter if I'm quickly tabbing through suggestions with a documentation preview. Whereas a list of suggestions without a documentation preview won't have that stutter.

**Comment by ms-jpq** [comment]
so like on all of them? even the ones that dont need resolving? 

or like just the LSP ones

**Comment by vxio** [comment]
Usually the LSP ones with a preview popup. The buffer suggestions are fine since there's no preview.

**Comment by ms-jpq** [comment]
treesitter, paths, ctags, all have previews, so do alot of custom ones too

**Comment by vxio** [comment]
Oh yeah, I was using LSP an example 😄

**Comment by vxio** [comment]
Interesting, this issue went away after a recent update. I'll close this for now, thanks!
