### ISSUE TITLE
textDocument/completion not supported with null-lsp

### ISSUE THREAD

**Issue by astridlyre** [ms-jpq/coq_nvim#347]
I am editing a markdown file and have null-ls setup to format it with prettierd. On every keystroke I get the error:

`method textDocument/completion is not supported by any of the servers registered for the current buffer`

This just started happening tonight after I updated COQ. When I stop null-ls the issue goes away, however I'd like to be able to enable null-ls to format my documents.

Config for null-ls looks like:

```lua
lspconfig['null-ls'].setup({})
```

I have also tried with:

```lua
lspconfig['null-ls'].setup(coq.lsp_ensure_capabilities({}))
```

**Comment by zeertzjq** [comment]
I can reproduce this in the latest Neovim version. When I installed an older version of Neovim and the error message is gone, so I think it is related to <https://github.com/neovim/neovim/pull/15926>.

**Comment by astridlyre** [comment]
Yes, I think you're right. Maybe COQ just needs to ignore any LS that doesn't support completion?

**Comment by ms-jpq** [comment]
yeah i should do that

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/366

here is a quick fix, a better solution will land later
