### ISSUE TITLE
Completion does not start with InsertEnter autocmd or <C-o>

### ISSUE THREAD

**Issue by mcchrish** [ms-jpq/coq_nvim#350]
I have an autocmd to start coq when entering insert mode:
```vim
autocmd InsertEnter * ++once lua require("coq").Now "--shut-up"
```

The command works but no completion. Completion only shows up the second time entering insert mode. The same behavior with `<C-o>:COQnow`.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/365
