### ISSUE TITLE
how to select sub-folders in path completion? 

### ISSUE THREAD

**Issue by pchaubal** [ms-jpq/coq_nvim#356]
Thanks for this amazing plugin. I already love it.

When i type a path, it shows me suggestions for sub-folders in folder. Is there a way to select the shown sub-folder/files from the secondary floating window?

**Comment by zeertzjq** [comment]
Currently this plugin uses Neovim native popup menu, not floating window, and I don't think Neovim supports multiple popup menus. Maybe this will be possible if this plugin switches to implementing its popup menu using floating window like what nvim-cmp does.

**Comment by pchaubal** [comment]
So as of yet, there is no way to select  folder and its sub-folder in this plugin? 

I am asking again to clarify that my question wasn't about a new feature request but rather if the current path selection can work as efficiently as needed. Right after selecting a folder name from suggestion, I hit enter and he completion menu goes away. To get the suggestions of sub-folders I have to hit space, then backslash to get the suggestion menu again. It would be great if I could select folder, sub-folder, sub-sub-folder all in a single action.

**Comment by zeertzjq** [comment]
Sorry for the misunderstanding.

**Comment by zeertzjq** [comment]
I think this is a duplicate of #214. That issue is a bit hard to understand though.

**Comment by zeertzjq** [comment]
Try checking out #357. In #357 completion for content of completed directory is shown if you pressed `/` to accept completion.

**Comment by pchaubal** [comment]
yes, #357 was exactly what I am looking for. Does it work with your latest commit?

**Comment by ms-jpq** [comment]
ok yeah this can be closed thanks to @zeertzjq  <3
