### ISSUE TITLE
Custom sources not working

### ISSUE THREAD

**Issue by williamboman** [ms-jpq/coq_nvim#358]
Hey! There seem to have been a regression with custom 3rd party sources, related to #293 (more context can be found in that thread). Whenever I have a custom source registered I run into the following error:

```
Error executing luv callback:
[string "<nvim>"]:62: client_id: expected number, got string
stack traceback:
        [string "<nvim>"]:62: in function 'on_resp_old'
        [string "<nvim>"]:82: in function 'on_resp'
        [string "<nvim>"]:234: in function 'callback'
        /Users/williamboman/.config/nvim/lua/wb/coq_3p/uuid.lua:43: in function </Users/williamboman/.config/nvim/lua/wb/coq_3p/uuid.lua:29>
```

You may find the implementation of the source [here](https://github.com/williamboman/nvim-config/blob/main/lua/wb/coq_3p/uuid.lua).

**Comment by Mte90** [comment]
Getting back on the discussion of the other ticket, 3p words because they don't use the `COQsources` variable as I looked in.
So I guess that they are managed in a different way compared to our custom sources.

**Comment by Mte90** [comment]
There are any updates for this?

**Comment by Mte90** [comment]
@ms-jpq any help for this?

**Comment by Mte90** [comment]
another ping, I have no idea how to patch it

**Comment by Mte90** [comment]
I removed that validation on https://github.com/ms-jpq/coq_nvim/blob/4cda35c003e646b5f6bdb312dab70106027fc3e5/coq/lsp/requests/lsp.lua#L62 and the custom source works.
I will do a PR for that but I am not sure if fix the issue or why that code is here but atleast after 7 months I am able to use my custom source again...

**Comment by Mte90** [comment]
So my patch for custom source was merged and now they should be working again.
Someone can double check?

**Comment by williamboman** [comment]
Cool :+1:! I don't use coq_nvim anymore so I won't be able to test, so I'll close this
