### ISSUE TITLE
COQ does not work to disable c-h and autostart problem

### ISSUE THREAD

**Issue by Plaoo** [ms-jpq/coq_nvim#359]
Hi I'm trying to disable, c-h, which I use to move between the tabs, the problem is that even entering the command
```let g:coq_settings = { 'keymap.jump_to_mark' : 'AAAAAAAAAAA' }```
nothing happens.
Another weird thing I've noticed is that if I add
lua require ("coq") at the end of plugin calls, actually not coq does not start at the beginning not even adding
```let g: coq_settings = {'auto_start': v: true}```
at the init.vim.

**Comment by rnprest** [comment]
@Plaoo What was your fix for this? I'm struggling with the exact same problem — wanting to overwrite the default C-h mapping

**Comment by rnprest** [comment]
I just opened a similar issue here https://github.com/ms-jpq/coq_nvim/issues/367
