### ISSUE TITLE
Sqlite traceback

### ISSUE THREAD

**Issue by emr-arvig** [ms-jpq/coq_nvim#36]
Hello. This is the current traceback when I am trying to use this

```
near "ON": syntax error
Traceback (most recent call last):
  File "/home/evanr/.config/nvim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/logging.py", line 31, in with_suppress
    yield None
  File "/home/evanr/.config/nvim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 21, in wrapper
    return await aw
  File "/home/evanr/.config/nvim/plugged/coq_nvim/coq/server/registrants/autocmds.py", line 167, in cont
    await stack.bdb.ft_update(buf.number, filetype=ft)
  File "/home/evanr/.config/nvim/plugged/coq_nvim/coq/databases/buffers/database.py", line 83, in ft_update
    await run_in_executor(self._ex.submit, cont)
  File "/home/evanr/.config/nvim/plugged/coq_nvim/.vars/runtime/lib/python3.9/site-packages/std2/asyncio/_prelude.py", line 41, in run_in_executor
    return await loop.run_in_executor(None, cont)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/evanr/.config/nvim/plugged/coq_nvim/coq/shared/executor.py", line 33, in submit
    return cast(T, fut.result())
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/evanr/.config/nvim/plugged/coq_nvim/coq/shared/executor.py", line 24, in cont
    ret = f(*args, **kwargs)
  File "/home/evanr/.config/nvim/plugged/coq_nvim/coq/databases/buffers/database.py", line 81, in cont
    _ensure_buffer(cursor, buf_id=buf_id, filetype=filetype)
  File "/home/evanr/.config/nvim/plugged/coq_nvim/coq/databases/buffers/database.py", line 21, in _ensure_buffer
    cursor.execute(
sqlite3.OperationalError: near "ON": syntax error

```

I am using the latest DEV release of NVIM and Python3.9.2

I can provide any other details that you need. 

Thanks!

**Comment by ms-jpq** [comment]
ohh, im pretty sure this is an issue where your version of sqlite is too old, but its really on my end because i used a sqlite feature introduced in 2018 [called upsert](https://www.sqlite.org/lang_UPSERT.html).

hummm, I should update the code to remove it

**Comment by emr-arvig** [comment]
Oh gross for some reason I _am_ using a really old version of sqlite3

```
> python3.9
Python 3.9.2 (default, Feb 20 2021, 20:59:40)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.11.0'

```
I will try to update this. I am not certain it makes sense to update the code - might be just extra work for you and I am just an edge case. Perhaps we can just say "hey - make sure you have sqlite3 version X or above"?

**Comment by ms-jpq** [comment]
no, i will update my code, you dont have to do anywork, im updating it right now <3

**Comment by ms-jpq** [comment]
please pull latest changes, it should be fixed now.

https://github.com/ms-jpq/coq_nvim/pull/37

**Comment by emr-arvig** [comment]
Thank you this is fixed now. I think it is worthwhile to note that I believe I had another error after I updated, which I didn't save. I did go ahead and just update sqlite3 - since I do not want to be on such an old version anyway. That is a _very_ old version.

Here is what worked for me 

```
$ sudo apt-get purge sqlite3 sqlite
$ wget https://www.sqlite.org/src/tarball/sqlite.tar.gz
$ tar xzf sqlite.tar.gz
$ cd sqlite/


$ sudo apt-get install build-essential

 $ export CFLAGS="-DSQLITE_ENABLE_FTS3 \
    -DSQLITE_ENABLE_FTS3_PARENTHESIS \
    -DSQLITE_ENABLE_FTS4 \
    -DSQLITE_ENABLE_FTS5 \
    -DSQLITE_ENABLE_JSON1 \
    -DSQLITE_ENABLE_LOAD_EXTENSION \
    -DSQLITE_ENABLE_RTREE \
    -DSQLITE_ENABLE_STAT4 \
    -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT \
    -DSQLITE_SOUNDEX \
    -DSQLITE_TEMP_STORE=3 \
    -DSQLITE_USE_URI \
    -O2 \
    -fPIC"
$ export PREFIX="/usr/local"
$ LIBS="-lm" ./configure --disable-tcl --enable-shared --enable-tempstore=always --prefix="$PREFIX"
$ make
$ sudo make install  # Install system-wide.


> python3.9
Python 3.9.2 (default, Feb 20 2021, 20:59:40)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.__file__
'/usr/lib/python3.9/sqlite3/__init__.py'
>>> sqlite3.sqlite_version
'3.37.0'

```

After this I completely exit neovim and everything is good. We are up and running now! Super fast. 🚀

**Comment by ms-jpq** [comment]
does make me wonder what else I added that wasn't sqlite `3.11.0` compatible, humm i should probably keep an eye for it.

are you on ubuntu 18? maybe I should make that a compatibility target.

wait ubuntu 18 has sqlite `3.22`, how was yours so old lol

**Comment by emr-arvig** [comment]
Unfortunately I am stuck on WSL1 - Ubuntu 16.04 due to a corporate environment.

Soooo yeah. No fun. Which is why I was like, hey do not change too much stuff on my account. Most people are now moving to WSL2 and iirc that is Ubuntu 18 by default - so this is definitely one of those edge cases. 

Regardless I appreciate you looking at it so soon. I have been enjoying using it all day and it is very fast and very nice to use.

Really I do think it should be good enough to note that you _must_ have a newer version of Sqlite. Most people should have that by default and it really was fairly trivial to build it from source anyway.

**Comment by ms-jpq** [comment]
oh jesus that sucks, haha yeah i should add it to the README.

thanks for the quick response :) 

I probably wont update for ubuntu 16 just because its already EOL
