### ISSUE TITLE
Popup Size customization not working?

### ISSUE THREAD

**Issue by zbirenbaum** [ms-jpq/coq_nvim#361]
I set y_max_len to a variety of different values but 16 results still always popup. I tried to customize 'match' to limit the number of matches returned to something like 8 for proximate lines, but this results in an error saying match is an extra key. I know my coq_settings are working an being read because the auto-start parameter is functioning properly, and the positions parameter seems to as well.

The size of the popup is very invasive currently, and 9/10 times I only need one of the first 5 results so it would be nice to be able to limit it....

**Comment by zbirenbaum** [comment]
Nevermind, y_ratio seems to have fixed it, but I am not even sure what y_max_len is supposed to do now so leaving it open in case anyone can tell me.

**Comment by zeertzjq** [comment]
May be a typo
<https://github.com/ms-jpq/coq_nvim/blob/a1ab14bc461da8314be8a548ed605d91fa0265ef/coq/server/registrants/options.py#L22>

**Comment by zbirenbaum** [comment]
> May be a typo
> 
> https://github.com/ms-jpq/coq_nvim/blob/a1ab14bc461da8314be8a548ed605d91fa0265ef/coq/server/registrants/options.py#L22

This is correct I think. I set the ratio to 0 and then I put y_max_len to be 2 and now the popup size is always 2.

**Comment by zeertzjq** [comment]
I means its a typo in COQ source code.

**Comment by zbirenbaum** [comment]
> I means its a typo in COQ source code.

I just figured that out lol, sorry for the confusion, I edited my above reply and figured it out. Thanks for figuring that out!

**Comment by zeertzjq** [comment]
But that behavior doesn't match DISPLAY.md:
```
The min of (y_max_len, y_ratio) wins.
```

I've opened #363 to fix this.

After #363 is merged, set the `y_ratio` to 1 instead to only use `y_max_len`.
