### ISSUE TITLE
Setting keymap.jump_to_mark isn't working

### ISSUE THREAD

**Issue by rnprest** [ms-jpq/coq_nvim#367]
Hey y'all, I'm really struggling to unbind the jump_to_mark keybind from `<C-h>` (I want to use `<C-h>` for a different mapping).

Here's what I have tried so far within my init.lua, with their errors.

- `g.coq_settings.keymap.jump_to_mark = '<leader>h'`
  - E5133: Error while calling lua chunk: init.lua:128: attempt to index field 'keymap' (a nil value)
- `g.coq_settings = { keymap.jump_to_mark = '<leader>h' }`
  - E5112: Error while creating lua chunk: init.lua:127: '}' expected near '='
- `g.coq_settings = { 'keymap.jump_to_mark': '<leader>h' }`
  - E5112: Error while creating lua chunk: init.lua:127: '}' expected near ':'

I'm currently setting the auto_start variable just fine, but for some reason this jump_to_mark keymap is just giving me loads of issues. Any help would be appreciated!

This is what I have (which works) for the coq_settings auto_start:
```
g.coq_settings = {
    auto_start = 'shut-up'
}
```

**Comment by jalsol** [comment]
```lua
vim.g.coq_settings = {
    ['keymap.jump_to_mark'] = '<C-F>'
}
```
This is a rushed attempt while trying to finish configuring things before going to bed. I'm not sure if this is good enough. But it works, and I can finally sleep.

**Comment by rnprest** [comment]
> ```lua
> vim.g.coq_settings = {
>     ['keymap.jump_to_mark'] = '<C-F>'
> }
> ```
> 
> This is a rushed attempt while trying to finish configuring things before going to bed. I'm not sure if this is good enough. But it works, and I can finally sleep.

BLESS. THANK YOU SO SO MUCH!! Didn't think of surrounding it with brackets

**Comment by ms-jpq** [comment]
yeah this is lua haha
