### ISSUE TITLE
Snippet placeholder inserted in middle of indentation level

### ISSUE THREAD

**Issue by erietz** [ms-jpq/coq_nvim#370]
I am on nvim 0.5 with treesitter disabled. I also have all of the default coq settings for debugging purposes.

When trying to insert a `if __name__ == '__main__' `  snippet, the content placed in the `pass` placeholder is inserted with three spaces before it and one space after it. I have my indent settings to insert 4 spaces in a python file.

Before:
![2021-10-23-130645_469x115_scrot](https://user-images.githubusercontent.com/11425271/138567191-3e50f132-4663-4c76-868e-5ee11712078b.png)

After:
![2021-10-23-130725_430x140_scrot](https://user-images.githubusercontent.com/11425271/138567192-01ca7af7-fe62-4d0a-8625-589275ac409e.png)

Note the final white space character after the print statement.

The same thing happens when trying to fill in a generic `if condition:` snippet.

Before:
![2021-10-23-131458_776x371_scrot](https://user-images.githubusercontent.com/11425271/138567260-edcaf788-3762-4e66-a15f-1cb6983b4e40.png)

After:
![2021-10-23-131728_185x99_scrot](https://user-images.githubusercontent.com/11425271/138567293-39ac76e9-cdf6-484f-95f6-2b5790bdb694.png)

It seems to occur if the place holder is the first thing on a line.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/427

fixed. reason was python's `str.expandtabs` is actually not `str.replace("\t", " " * size)`, but rather tries to align text.

which `coq` already does, so on some configurations, the twice aligned results are wrong
