### ISSUE TITLE
Snippet edit marked moves cursor to the wrong area

### ISSUE THREAD

**Issue by Nazushvel** [ms-jpq/coq_nvim#372]
I am using a clean neovim install, only configs added are Plug, the main plugin and snippets.

The behavor I am seeing is when I add a snippet and use C-h to move to the new mark it will work and move for some areas however on new lines the cursor will appear at the beginning of the line in front of the indent.
Below are some examples, because of my screenshot program the cursor changes during screenshots so I will mark which parts are in insert mode

before C-h:
![image](https://user-images.githubusercontent.com/24550564/138611818-ce8b9625-0f60-4c3b-94d6-f528d0da1c17.png)

After C-h (still in insert mode):
![image](https://user-images.githubusercontent.com/24550564/138611431-1243fb6f-9b5a-4799-82be-a60391491bea.png)

After exiting insert:
![image](https://user-images.githubusercontent.com/24550564/138611444-6b04d3fc-6f07-4a2a-903c-c06a7dbcdc43.png)

I have also see some strange behavor when attempted to use #!/bin/sh where it will insert the cursor in the wrong place for the marked area:

![image](https://user-images.githubusercontent.com/24550564/138611523-17cbc15b-7612-49e8-9c26-3dd1069e05b1.png)

After C-h (Still in insert mode):
![image](https://user-images.githubusercontent.com/24550564/138611536-952b7c41-197a-4d94-be0d-9abe7632f81e.png)

In the second picture the insert mode cursor is appear before the / not after.

I think these might be related but they could be different issues. I also have tested this with other languages with the same effect

**Comment by zeertzjq** [comment]
Does this also happen if you set `coq_settings.keymap.jump_to_mark` to some other key?

**Comment by erietz** [comment]
This looks similar to issue #370. I tried both with the default `<c-h>` and (the more intuitive) `<c-l>`.

**Comment by Nazushvel** [comment]
Yup same on my end, a key change seems to not change anything. I also have attempted switching the tab spacing as well as another terminal and inside/outside of tmux.

**Comment by Nazushvel** [comment]
After working on my own snippet file today I think I found what is causing this behavor.

It appears any snippet created with a tab for indenting will start the cursor at the beginning of the line.

Any snippet that uses 4 spaces will start with the cursor between the 3rd and 4th space.

So it appears that this may be something with how the snippets are interpreting the tabs/spaces in the snippet files.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/issues/370#issuecomment-1004525046

**Comment by Nazushvel** [comment]
I don't believe this has been resolved yet. It looks to still be working incorrectly in bash and is still having issues with python. Any chance we could get this reopened and looked at? This is really preventing my from switching to this fully which is a shame because I really am enjoying it.

With python for example when attempting to do and if statement the jump on line two will work however there is still a space at the end of what is written as well as it only is 3 spaces in front instead of 4:
![image](https://user-images.githubusercontent.com/24550564/148329721-9f08ec03-c556-4435-b805-0d4c341525fe.png)

Bash seems to be having the same issue as before. When attempting to do an if statement it does not follow the indenting at all and starts it at the beginning of the line. It is also having the same issue with moving the cursor one in front of where it should on the /bin/bash:
![image](https://user-images.githubusercontent.com/24550564/148329903-67e32ec9-eadd-4703-b86d-58f2d7f31f78.png)
![image](https://user-images.githubusercontent.com/24550564/148330389-41e196bc-107e-44df-a1f0-085d050d0d1d.png)
