### ISSUE TITLE
Python Error when initializing plugin: ImportError: cannot import name 'nullcontext'

### ISSUE THREAD

**Issue by makeaweli** [ms-jpq/coq_nvim#373]
I received an error when accessing any of the plugin commands `COQnow`, `COQdeps`, etc.

I did make sure that python3 virtualenv was updated and installed, according to the README:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jkalawe/.vim/plugged/coq_nvim/coq/__main__.py", line 3, in <module>
    from contextlib import nullcontext, redirect_stderr, redirect_stdout
ImportError: cannot import name 'nullcontext'
```

**Comment by zeertzjq** [comment]
Your Python version is too old.
<https://github.com/ms-jpq/coq_nvim#install>:
> Minimum version: python:3.8.2, nvim: 0.5, sqlite: recentish

**Comment by makeaweli** [comment]
Apologies. User error. Please close this issue.

**Comment by zeertzjq** [comment]
Maybe the code checking for Python version can be moved before some imports.

**Comment by ms-jpq** [comment]
oh wow you are on python < 3.7, ok i didnt even think to support a notification for 3.6 haha.

sure ill fix

**Comment by ms-jpq** [comment]
fixed
