### ISSUE TITLE
Incorrect indentation for multiline snippets

### ISSUE THREAD

**Issue by cionx** [ms-jpq/coq_nvim#374]
I defined the following snippet for test purposes (indentation via tabs):

```snip
snippet test
	start
		indent
	stop
```

If I use this snippet at the end of an already indented line, then the subsequent inserted lines are not correctly indented; this can be seen in the left image. The right image shows the expected result.  (In the pictures, indentation via tabs is displayed by underscores; tabwidth is two spaces.)
![collage][1]

[1]: https://user-images.githubusercontent.com/7231796/138782335-9adc30bc-426c-4600-a706-0c11b1c563c9.png

**Comment by ms-jpq** [comment]
yeah i dont think i got the tabs right

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/issues/370#issuecomment-1004525046

probably fixed it

**Comment by predmijat** [comment]
Hi,

I have an issue which kinda looks like this one. I'm new with nvim so if this is not related to coq_nvim, don't get mad :)

<img width="410" alt="Screen Shot 2022-01-05 at 11 19 37 PM" src="https://user-images.githubusercontent.com/8684411/148297671-b659b943-ec50-48ee-b58b-de7d4424682f.png">

If I type `ifer` and then `<Tab>` for `if err != nil` snippet, I get messed up indentation - there's a space as first character, even though (I think) I've configured nvim not to have spaces in .go files.

```
vim.cmd [[
  augroup go
    autocmd!
    au FileType go setlocal tabstop=8 noexpandtab shiftwidth=8 softtabstop=8
  augroup end
]]
```

Options after I open .go file:
`:set tabstop?` - `tabstop=8`
`:set noexpandtab?` - `noexpandtab`
`:set shiftwidth?` - `shiftwidth=8`
`:set softtabstop?` - `softtabstop=8`

If I insert snippet outside of `main`, it looks good.

Let me know if any other info is needed.

Thanks!

**Comment by cionx** [comment]
The problem seems to still be there. I just tested the current version (commit fbd547b70974ed43825d900c2a1e2ab1c9fbc67d) with the following snippet that I use for LaTeX:
```snip
snippet equation
	\\[
		$0
	\\]
```
By repeatedly applying this snippet I get the output in the left picture. But I would expect the output to look as in the right picture.
![result][1] ![expected][2]

[1]: https://user-images.githubusercontent.com/7231796/148598801-46fd1f8d-d0b0-4d53-bd1c-48dad297351c.png
[2]: https://user-images.githubusercontent.com/7231796/148598798-381be1e3-885c-47de-8502-09b485e5e30a.png

**Comment by yueyingjuesha** [comment]
I would say coq_nvim definitely breaks some indentation
when I type "func main(){<CR>}" in golang file, it is not automatically indented like original neovim behavior 
@ms-jpq

**Comment by predmijat** [comment]
Is this snippets thing working as expected for anyone? What am I doing wrong here:

https://user-images.githubusercontent.com/8684411/173685526-5670f94c-2ea5-4caa-afba-0de2f430b513.mov

**Comment by predmijat** [comment]
Pretty please?
