### ISSUE TITLE
wrong completion of "that" and "the"

### ISSUE THREAD

**Issue by mathjiajia** [ms-jpq/coq_nvim#378]
See the two screenshots below.

When I type "the", the first result is "that".
<img width="1071" alt="Screen Shot 2021-10-27 at 1 58 04 PM" src="https://user-images.githubusercontent.com/35106942/139008326-05f0fffb-42cb-43ea-bfba-1eeac4a3248f.png">

Similarly, when I type "that", the first result is "the".
<img width="1131" alt="Screen Shot 2021-10-27 at 1 58 18 PM" src="https://user-images.githubusercontent.com/35106942/139008337-6285757b-acdb-4689-8749-dbf2e2f38c0c.png">

Am I missing something?

**Comment by ms-jpq** [comment]
no, what should it say instead?

the only matching word is "the" or "that", since there is a filter to not output the same word under cursor.

**Comment by ms-jpq** [comment]
so unless there is another better match for example when you the in "the" and you have the word "thesaurus" somewhere in there, it would be ranked above "that"

**Comment by ms-jpq** [comment]
it's not an exact prefix match, unlike other plugins because humans are quite fallible creatures

**Comment by mathjiajia** [comment]
Oh, I see.
Thanks.

**Comment by ms-jpq** [comment]
<3
