### ISSUE TITLE
COQstats result in __main__.py error

### ISSUE THREAD

**Issue by thanhdn1989** [ms-jpq/coq_nvim#382]
I followed the [installation guide](https://github.com/ms-jpq/coq_nvim#install). But COQ failed to run, when running the `COQstats` command i faced this error:

![image](https://user-images.githubusercontent.com/16373244/139515151-6259d3a0-ab54-4641-b7da-9df0d384c308.png)

I have check that line of code that it complaint about _IN_VENV
![image](https://user-images.githubusercontent.com/16373244/139516229-8f50c2df-d293-49b6-8a06-89c4bc17e1a9.png)
but running `/bin/python3` is fine for me (i'm running 3.8.10)

**Comment by Tomburgs** [comment]
Make sure you've ran `:COQdeps`.

**Comment by erturk** [comment]
This should be added to install documentation.

**Comment by ms-jpq** [comment]
fixed
