### ISSUE TITLE
Close completion popup

### ISSUE THREAD

**Issue by TitaniumHocker** [ms-jpq/coq_nvim#383]
I'm using [lsp_signature](https://github.com/ray-x/lsp_signature.nvim) ext and have some trouble -
![image](https://user-images.githubusercontent.com/37049574/139561871-c411ee93-976d-4c85-bd4b-85252fe03de9.png)

As you can see on screenshot, completion popup overlaps signature popup. The first solution I came up with is to close completion window, but I didn't found way to do this. If you have any ideas how to handle this another way - I am ready to listen.

UPDATE:
I thought a little about alternative solutions and came to the idea - if it was possible to add `,` and `(` to the exceptions for the completion popup to appear, then it would not prevent me from reading the signature.

**Comment by zeertzjq** [comment]
Press `CTRL-E`.

See `:h popupmenu-keys`.

**Comment by TitaniumHocker** [comment]
> Press `CTRL-E`.
> 
> See `:h popupmenu-keys`.

Thx
