### ISSUE TITLE
Suggestions overlapped with virtual text of lsp_signature

### ISSUE THREAD

**Issue by leelavg** [ms-jpq/coq_nvim#385]
hi,

- thanks a lot for this plugin and I was able to get this up and running with relatively less effort compared to other completion plugins and been using it for sometime
- i already looked at #101 but can still see the issue. Please find below details
- Versions:
```
# gl -n 1
* fcbdeef - (11 hours ago)  (HEAD -> coq, origin/coq, origin/HEAD) CI (AGP) - 2021-11-02 00:32 <agp-bot>

# nvim -v | head -n 1
NVIM v0.5.1
```
- Relevant config section from my [init.vim](https://github.com/leelavg/dotfiles/blob/master/config/init.vim)
``` lua
---
autocmd VimEnter * :COQnow -s
---
vim.g.coq_settings = {
    keymap = {
        jump_to_mark = '', -- Don't mess up tmux-navigator
    },
    display = {
        icons = {
            mode = 'none',
        },
    },
    clients = {
        tags = {
            enabled = true,
            short_name = 'T',
        },
        tree_sitter = {
            enabled = false,
        },
        buffers = {
            same_filetype = true,
            short_name = 'B',
        },
        tmux = {
            enabled = false,
        },
        tabnine = {
            enabled = false,
        },
        lsp = {
            short_name = 'L',
        },
        snippets = {
            -- Don't bother about snippets
            warn = {},
        },
    },
}
---
require "lsp_signature".on_attach({
  bind = true,
  handler_opts = {
      border = "single"
      }
}, bufnr)
---
local coq_lsp = require('coq').lsp_ensure_capabilities
---
lspconfig[server].setup(coq_lsp({ on_attach = on_attach }))
---
```
![virtual](https://user-images.githubusercontent.com/37169113/139838291-d626c530-5f2e-467f-a3b6-5b762f426395.png)

- Let me know if more info is required or if I'm configuring something wrong, thanks in advance.

**Comment by zeertzjq** [comment]
I think you should report this to `lsp_signature`, because the popup menu position of COQ is decided by Nvim, while the floating window position of `lsp_signature` is decided by itself.

**Comment by leelavg** [comment]
Ack, the attached issue #101 screen capture states that pop-up menu appears after lsp_signature so I raised issue here.

Edit: btw, lsp_signature has option to auto select window position and in those cases when there's space after current line both pop-up menu and signature doc is being displayed after the line.

**Comment by leelavg** [comment]
Removed lsp_signature plugin
