### ISSUE TITLE
[LSP Completion] The lsp completion not work as expected

### ISSUE THREAD

**Issue by hiberabyss** [ms-jpq/coq_nvim#389]
When I select the lsp item, the following content is filled, I only want the function name:

```
  Uint64TensorProcessor(const int &msg, const int *fd, int *tensor) -> void
```

![image](https://user-images.githubusercontent.com/2898670/140710519-fb4ee055-bd8d-4e5c-80c1-8fc19821bfff.png)

**Comment by LamprosPitsillos** [comment]
#407 
same here

**Comment by ms-jpq** [comment]
closing cuz dup, i am working on a fix :)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/425
