### ISSUE TITLE
Is there an option to automatically select the first suggestion?

### ISSUE THREAD

**Issue by cjnucette** [ms-jpq/coq_nvim#39]
If the first suggestion is the one that I want, I just want to press `<cr>`. Right now I need to press `<tab>` and then `<cr>`.

**Comment by emr-arvig** [comment]
Would also be nice to just hit TAB to complete the selection. This is what I am used to. I am not understanding how to do this with the key bindings documentation.

**Comment by Shougo** [comment]
Hm. `set completeopt+=noinsert` does not work.
`coq_nvim` seems overwrite `completeopt`.

**Comment by ms-jpq** [comment]
hummm, good point, I will add a hotkey. 

some `completeopt` are overwritten because they interfered with `nvim_buf_lines_event`, I forgot which one it was though.

**Comment by YodaEmbedding** [comment]
Related: this avoids the need to press `<CR><Esc>` so that you can just do `<Esc>`:

```vim
inoremap <silent><expr> <Esc> pumvisible() ? (complete_info().selected == -1 ? "\<Esc>" : "\<C-y>\<Esc>") : "\<Esc>"
```

(Be sure to apply this after coq_nvim sets up its keybindings, or [disable them](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/KEYBIND.md#custom-keybindings) and rewrite your own.)

**Comment by zeertzjq** [comment]
This may work:
`ino <silent><expr> <CR> pumvisible() ? (complete_info().selected == -1 ? "\<C-n><C-y>" : "\<C-y>") : "\<CR>"`

**Comment by zeertzjq** [comment]
Removing `noselect`  from `completeopt` and keeping `noinsert` may also work. You need to do this after the plugin is loaded though.

**Comment by PHSix** [comment]
> Removing `noselect` from `completeopt` and keeping `noinsert` may also work. You need to do this after the plugin is loaded though.

I found that can use neovim defer_fn api to remove noselect from completeopt automatically, like: 
```lua 
vim.defer_fn(
  function()
    vim.o.completeopt = "menu,preview,noinsert,menuone"
  end,
  1000
)
```

**Comment by dnaaun** [comment]
I can also confirm that removing `noselect` from `completeopt` doesn't break coq completion at all. @ms-jpq , if you agree, I can submit a PR removing `noselect` from:

https://github.com/ms-jpq/coq_nvim/blob/05268a8657d47b0ee6cb132cdc300f28565986df/coq/server/registrants/options.py#L75

That way, users' preference regarding whether they want `noselect` in `completeopt` are retained when coq is loaded.

**Comment by zeertzjq** [comment]
Maybe this can become a configurable option like what nvim-cmp has ([this](https://github.com/hrsh7th/nvim-cmp#preselect-type-cmppreselectmode) or [this](https://github.com/hrsh7th/nvim-cmp#completioncompleteopt-type-string)).

**Comment by dnaaun** [comment]
> Maybe this can become a configurable option like what nvim-cmp has

Why create an additional option when the user can instead modify `completeopt`, a builtin option?

**Comment by zeertzjq** [comment]
I just think simply removing `noselect` from the code changes the default behavior.

**Comment by dnaaun** [comment]
> I just think simply removing "noselect" from the code changes the default behavior.


Yes, this would change _coq_'s default behavior indeed.

**Comment by ms-jpq** [comment]
### coq_settings.keymap.pre_select

Always select first result. Will need to frequently hit manual exit completion with `<c-e>` if chosen.

**default:**

```json
false
```

---

https://github.com/ms-jpq/coq_nvim/pull/300
