### ISSUE TITLE
Cannot remap Coq.nav_mark() to other key

### ISSUE THREAD

**Issue by john-front** [ms-jpq/coq_nvim#390]
I have <C-h> mapping for something else but COQ.Nav_mark() uses the same key. I want COQ.Nav_mark() to use some other key binding but don't know how to do it. My setting right now is:

`" Set recommended to false
let g:coq_settings = { "keymap.recommended": v:false, "auto_start": "shut-up" }

" Keybindings
ino <silent><expr> <Esc>   pumvisible() ? "\<C-e><Esc>" : "\<Esc>"
ino <silent><expr> <C-c>   pumvisible() ? "\<C-e><C-c>" : "\<C-c>"
ino <silent><expr> <BS>    pumvisible() ? "\<C-e><BS>"  : "\<BS>"
ino <silent><expr> <CR>    pumvisible() ? (complete_info().selected == -1 ? "\<C-e><CR>" : "\<C-y>") : "\<CR>"
ino <silent><expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
ino <silent><expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<BS>"
nmap <C-9> <C-\><C-N><Cmd>lua COQ.Nav_mark()<CR>
vmap <C-9> <Cmd>lua COQ.Nav_mark()<CR>
`
PS: the keymaps are automatically removed here when I save but I have them in my setting.

**Comment by 4slimbu** [comment]
Try this:
lua << EOF
    vim.g.coq_settings = {
        auto_start = 'shut-up',
        keymap = {
            jump_to_mark = '\<C-your_key\>'
        }
    }
EOF

**Comment by zeertzjq** [comment]
Well, `<C-m>` is not a good example, because Nvim cannot distinguish `<C-m>` and `<CR>`.

**Comment by 4slimbu** [comment]
> Well, `<C-m>` is not a good example, because Nvim cannot distinguish `<C-m>` and `<CR>`. 
@zeertzjq  edited :)

**Comment by alexzanderr** [comment]
use this
```vimL
	let g:coq_settings = {
		\ "keymap.recommended": v:false,
		\ "keymap.jump_to_mark": "<nop>",
        \ }

```
for me its working.
