### ISSUE TITLE
COQdeps is required but does nothing

### ISSUE THREAD

**Issue by Eugene-msc** [ms-jpq/coq_nvim#393]
Every time I try to run `:COQnow` it shows this message, seemingly requiring running `:COQdeps`
```
Please update dependencies using :COQdeps
-
-
Dependencies will be installed privately inside `/home/user/.vim/plugged/coq_nvim/.vars`
`rm -rf coq_nvim` will cleanly remove everything
```

But when I run `:COQdeps` it just shows
```
COQ EXITED - 1
```
And nothing else. I tried looking at `:messages` thinking that maybe I just see the last line of the output, but this one line is all there is

**Comment by DhruvDh** [comment]
Do look at #337 once

**Comment by Eugene-msc** [comment]
https://github.com/ms-jpq/coq_nvim/issues/337#issuecomment-970669686

**Comment by fwolfst** [comment]
(TL;DR stock ubuntu 22.04) install `python3-venv` and/or the dependencies manually.
