### ISSUE TITLE
Feature Request: Integrate with fine-cmdline.nvim

### ISSUE THREAD

**Issue by yingzhu146** [ms-jpq/coq_nvim#398]
Hey, thanks a ton for your awesome plugin!

Would be awesome to get to work with https://github.com/VonHeikemen/fine-cmdline.nvim and have it provide visually appealing completion support similar to https://github.com/gelguy/wilder.nvim.

Thanks a ton!

**Comment by ms-jpq** [comment]
sorry i cant support it, i am really short on bandwidth and i have to limit feature creep
