### ISSUE TITLE
Request for simple working configuration

### ISSUE THREAD

**Issue by ratheesh** [ms-jpq/coq_nvim#4]
This plugin is interesting.
But, I am unable to configure auto-complete with LSP.

Following is my minimal vimrc

```vimrc
call plug#begin('~/.vim/plugged')

Plug 'neovim/nvim-lspconfig'
Plug 'ms-jpq/kok.nvim', {'branch': 'kok', 'do': ':UpdateRemotePlugins'}

call plug#end()

lua <<EOF

require("lspconfig").gopls.setup{}
require("kok/recommends").all()

EOF  ⏎
```
I am unable to see autocomplete without the KoKstart command just like other autocomplete plugins.

- [ ] I am not sure where to put the config.json file. Can you mention this in README?
- [ ] Can you please put minimal working vimrc configuration in README with few sources enabled.
- [ ] The hyperlinks in README are not working (probably not updated after the plugin got renamed). Can you please update?

**Comment by ms-jpq** [comment]
sorry this is a work in progress and im going to be changing alot of stuff later on, 

please dont use this repo for now :(

**Comment by ratheesh** [comment]
Thanks. Hope that this will be ready soon.
