### ISSUE TITLE
Autocomplete puts a newline

### ISSUE THREAD

**Issue by Plaoo** [ms-jpq/coq_nvim#401]
Hi, when I select a suggestion from the autocomplete table, if I select it with enter the cursor is placed in a new line.
Is it possible that my choice is directly reproduced on the code or is there a button that allows me to select the suggestion without creating a new line or adding a space?

**Comment by IllustratedMan-code** [comment]
I can't reproduce this. Can you give use more details about setup? Does it happen for every suggestion? It could be possible that the completion you are selecting contains a newline.

**Comment by Plaoo** [comment]
Hi, you can find my complete configuration here [config](https://github.com/Plaoo/nvim-config ).and this is the problem:
[video](https://asciinema.org/a/W8u3kKZaomKB27nGpCEIFGBgZ)

**Comment by CRAG666** [comment]
That behavior is probocato by your auto pairs plugin. in fact it happens with many complements of this style it would be useful if this is documented and how to be able to use coq in conjunction with some auto pairs

**Comment by Plaoo** [comment]
Yes thanks

**Comment by fedya-eremin** [comment]
Felt it now, if anyone would need this in future, e.g in config of nvim-autopairs you should set
`map_cr = false`
Looking for real fix
