### ISSUE TITLE
[Question] How to declare these custom snippet

### ISSUE THREAD

**Issue by rewhile** [ms-jpq/coq_nvim#404]
I want to create a snippet that expands under certain condition for example:

```
snippet /
if vimtex#syntax#in_mathzone()
  \\frac{$1}{$2}
```

I also notice that given the same placeholder does not auto copy
```
snippet beg
  \\begin{$1)
    $2
  \\end($1}$0
```

Expectation when I type abc:
```
\begin{abc)
  $2
\end(abc}$0
```

Also is there a way to have autotrigger snippet?

**Comment by lftabera** [comment]
It seems that linked tabstops do not work. 
I can make it work with placeholders
```
snippet begin
    \\begin{${1:proof}}
        ${2: body}
    \\end{${1:proof}}${0: }
```

when you call the snippet, do not write directly, but press jump_to_mark shortcut (<c-h> by default). Then, you write the 'abc' in your example in the command line. It is not as nice visually as other snippet plugins but works.

**Comment by evanhorn** [comment]
I don't know if this is related, but I am unable to completely duplicate the Python class definition ("cl") example in the documentation. The expansion correctly expands the class name everywhere EXCEPT for the docstring. Additionally, cycling through the tabstops never brings me to the docstring or the super call (tabstops 3 and 5) for that snippet.

If this is not related, then please let me know, and I will open another issue.

**Comment by ms-jpq** [comment]
arbitrary code execution is forbidden by design for safety reasons.

the `tabstop` requiring placeholder thing seems like a bug in the parser. i will look into it
