### ISSUE TITLE
Cannot disable all keybinds

### ISSUE THREAD

**Issue by lyndsysimon** [ms-jpq/coq_nvim#406]
[The documentation](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/KEYBIND.md#custom-keybindings) leads me to believe that the setting `keymap.recommended = false` will disable all keybinds, but I've found that there are some that are still bound.

In my use case, `keymap.jump_to_mark` remains set to `<c-h>`, which I have already bound to `<c-w><c-h>` ("move one spilt to the left"). I resolved this issue by setting ~~`keymap.jump_to_mark = '<nop>'`~~ as a workaround.

Correction - the above workaround sets the key to the sequence `<nop>`, which causes issues entering anything in angled brackets. I'm now using `keymap.jump_to_mark = ''`. That hasn't caused any obvious issues yet.

I propose adding a `keymap = nil` to prevent binding any keys at all.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/commit/79ab36294f572f0e1304255a89f8cc29aca094d5

made it more explicit in the helpdocs
