### ISSUE TITLE
I get this error when I try to install

### ISSUE THREAD

**Issue by CRAG666** [ms-jpq/coq_nvim#408]
Getting requirements to build wheel: finished with status 'error'                              
  ERROR: Command errored out with exit status 1:                                                 
   command: /home/crag/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/bin/python
3 /home/crag/.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-
packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpc9kbh7
sv                                                                                               
       cwd: /tmp/pip-install-oynyh2ic/pyyaml_959a45070cdf4f508a8ca9f6937a6566                    
  Complete output (6 lines):                                                                     
  running egg_info                                                                               
  writing lib3/PyYAML.egg-info/PKG-INFO                                                          
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt                          
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt                                  
  failed to import Cython: /tmp/pip-build-env-mj6kan48/overlay/lib/python3.10/site-packages/Cytho
n/Compiler/Scanning.cpython-310-x86_64-linux-gnu.so: failed to map segment from shared object    
  error: Cython does not appear to be installed                                                  
  ----------------------------------------                                                       
WARNING: Discarding https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b0299
91d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz#sha256=607774cbba28732bfa802b54baa7484215f53099
1055bb562efbed5b2f20a45e (from https://pypi.org/simple/pyyaml/) (requires-python:>=2.7, !=3.0.*, 
!=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*). Command errored out with exit status 1: /home/crag/
.local/share/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/bin/python3 /home/crag/.local/sha
re/nvim/site/pack/packer/start/coq_nvim/.vars/runtime/lib/python3.10/site-packages/pip/_vendor/pe
p517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpc9kbh7sv Check the logs for f
ull command output.                                                                              
ERROR: Could not find a version that satisfies the requirement PyYAML==5.4.1 (from versions: 3.10
, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1, 5.1.1, 5.1.2,
 5.2b1, 5.2, 5.3b1, 5.3, 5.3.1, 5.4b1, 5.4b2, 5.4, 5.4.1, 6.0b1, 6.0)                            
ERROR: No matching distribution found for PyYAML==5.4.1                                          
Installation failed, check :message

**Comment by lftabera** [comment]
Not sure if is an error or you are supposed to have installed.

Try installing python3-yaml or a similar package

**Comment by CRAG666** [comment]
In the end, no solution helped, it was enough just to remove the version of the requirements.txt
