### ISSUE TITLE
[Question] Completion menu _only_ on action, not on keystroke

### ISSUE THREAD

**Issue by MiragonMx** [ms-jpq/coq_nvim#409]
Started using and configuring coq very recently and couldn't get around this:
Is it possible to trigger the completion menu only from a specific action (default <C-space> and _not_ on every keystroke? Couldn't find anything in that regard in the docs..

**Comment by Osrepnay** [comment]
#44 maybe?

**Comment by MiragonMx** [comment]
True, will close this and follow the other, thanks for pointing it out!
