### ISSUE TITLE
Didn't install coq.artifacts, still complains

### ISSUE THREAD

**Issue by tonekk** [ms-jpq/coq_nvim#411]
```
⚠️  No compatible snippets found, try updating `coq.artifacts`
```

is shown a startup. How can I disable this?

**Comment by uf5** [comment]
As a workaround you can create an empty snippet file with ```:COQsnips edit``` and then compile it with ```:COQsnips compile```.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SOURCES.md

I kinda put it in a bad place, set `coq_settings.clients.snippets.warn` to an empty array.
