### ISSUE TITLE
Bug: <c-space> throws an error

### ISSUE THREAD

**Issue by LoadingBG** [ms-jpq/coq_nvim#417]
Every time I press `<c-space>` for manual autocompletion I get the following error:
![image](https://user-images.githubusercontent.com/51295058/147826422-e1751499-eafe-459c-b98f-bd149f0ed808.png)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/424

I added a user config validation to make sure to catch the `coq_settings.match.max_results < 0` before it gets there. so it's more user friendly
