### ISSUE TITLE
COQnow throws error regarding \u2728 (sparkles character??)

### ISSUE THREAD

**Issue by henriqpsantos** [ms-jpq/coq_nvim#42]
Running COQnow, on a recent reinstall with Packer (after running COQnow) with both coq + the snippets codebase gives this error:

![image](https://user-images.githubusercontent.com/2131630/129622725-690e4452-70c5-43e4-9751-dc04f9a74c02.png)

Looking up \u2728 returns the sparkles emoji?? Error is the same on neovide as is on windows terminal, plugin is on the start folder. Error is after the first character is inserted.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/43

can you please pull latest to test out if my fix worked, i dont have a windows machine, and I think windows either needs UTF-8 (under an obscure flag) or UTF-16, but since neovim has utf8 support builtin, i want to see if just utf8 works

**Comment by henriqpsantos** [comment]
I believe that fixed it, cheers! Another fairly small issue is that messages sometimes get cut off by a ^M:

![image](https://user-images.githubusercontent.com/2131630/129632348-a20a1b17-48b4-42dc-8943-11a5cd57502d.png)

I know this is a windows thing, but maybe on your end there is a fix?
Edit: Also, holy fucking shit that was fast xD

**Comment by ms-jpq** [comment]
so basically everything in the greetings comes from [this file](https://github.com/ms-jpq/coq_nvim/blob/coq/artifacts/helo.yml)

I am not sure where the `^M` comes from, it seems to be from after the `✨`,  but there is no newline after the `✨`, so thats kinda weird. Ill probably need to set up a VM later to debug it.

if it bugs you, you can use the `-s, --shut-up` flag when calling `:COQnow` to stop the greetings.

btw, the `☐☐` you see there is suppose to be hello from a foreign language, i added a bunch that basically greets you from around the world, and picks a random one every time you launch `coq.nvim`

judging by the length tough, you got `你好`

**Comment by ms-jpq** [comment]
Ill close this because thats a relatively minor issue and Ill just make a mental note of it
