### ISSUE TITLE
How to enable coq only manually?

### ISSUE THREAD

**Issue by fecet** [ms-jpq/coq_nvim#421]
Disable automatic popup menu for specific teletype, and only show up when press "C-space"

**Comment by zeertzjq** [comment]
There is already an issue for this: #44

**Comment by ms-jpq** [comment]
i actually just added this in today.

finally got some time to work on stuff :)

since i am outside, will post the docs here later

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/blob/coq/docs/COMPLETION.md
