### ISSUE TITLE
Question: Specific reason behind 'manual_complete' mapping also in 'Normal' mode?

### ISSUE THREAD

**Issue by skoenen** [ms-jpq/coq_nvim#438]
I have mapped `za` to `<C-space>` to have a convenient way to open and close a fold.

So i thougth, why not set the manual complete to `<C-p>` instead. Because it is the default mapping for completion in vim in __Insert__ mode. So it does not interfere with settings in __Normal__ mode.
So I have a mapping for the fzf plugin to find a file in the current project on `<C-p>` in __Normal__ mode and then the manual completion in __Insert__ mode.

But this specific line is preventing this:
https://github.com/ms-jpq/coq_nvim/blob/9546c14f6664df71b9427b38fcebb7800b69799e/coq/server/registrants/options.py#L70

Therefore my question:
Specific reason behind 'manual_complete' mapping also in 'Normal' mode?

**Comment by Diegovsky** [comment]
I don't like this either. I use `<C-space>` in normal mode to access buffers and this is not very good. Maybe making this optional by removing it from the code and adding an entry in [the custom keybindings section](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/KEYBIND.md#custom-keybindings) would be better?

Or adding it to the [recommended keymaps section](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/KEYBIND.md#coq_settingskeymaprecommended) to avoid confusion.

I'm not sure how many people use this recommended binding so this could be a bad idea if we break other people's setup :(

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/blob/coq/docs/KEYBIND.md

`coq_settings.keymap.manual_complete_insertion_only` set this to true to fix this issue :D

**Comment by Diegovsky** [comment]
Thank you!
