### ISSUE TITLE
Disable when writing Markdown

### ISSUE THREAD

**Issue by sirupsen** [ms-jpq/coq_nvim#448]
Hey, thanks for a fantastic autocompleter :)

I can't find a good way to disable autocompletion in Markdown files with autostart on. 👀 

The completions can be a bit overwhelming when writing prose. I can, of course, set autostart to false and manually enable, but that doesn't seem optimal either... It would be amazing to have a way to disable in various contexts, or even a way to shut down coq for that filetype

**Comment by kaiuri** [comment]
@sirupsen 
If you're using a plugin manager that allows for lazy-loading you can define it when writing the specifications for coq_nvim e.g.

Packer

```lua
require('packer').startup {
  function(use)
    use { 'ms-jpq/coq_nvim', ft = { 'lua', 'rust', 'go', --[[... etc, keep markdown out ]]} }
  end,
}
...

**Comment by sirupsen** [comment]
Ahhhh yes! Thanks @urikaoli
