### ISSUE TITLE
Jump to next snippet location with Tab

### ISSUE THREAD

**Issue by DFreds** [ms-jpq/coq_nvim#45]
Is this possible? I tried setting jump to mark to both `<tab>` and `<c-n>` but it didn't seem to change it.

```
vim.g.coq_settings = {
  ["keymap.jump_to_mark"] = "<c-n>"
}
```

**Comment by ms-jpq** [comment]
yes, but you need to unmap `<tab>` first

[details here](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/KEYBIND.md)
