### ISSUE TITLE
Custom Source in Python

### ISSUE THREAD

**Issue by rajaravivarma-r** [ms-jpq/coq_nvim#463]
Hi, thanks for the great work.

I am trying to switch from deoplete, as I found your plugin to be little more robust and lot more fast.

It was easy to write my own custom completion in deoplete, because it was just a hook in Python and it was easier.

I see that the custom sources should be written in Lua which is awesome, but I really miss Python's standard library. So I just wanted to check if there are any plans to support Python to write custom sources in the future.

**Comment by Watynecc** [comment]
Wdym ? By using Neovim Native LSP you can add pyright/jedi language server into coc.nvim

**Comment by rajaravivarma-r** [comment]
@Watynecc No I'm not talking about add Python LSP. I want to add a **custom source** using Python instead of Lua.

Fox example, I would like to add auto complete for files, so I will store a list of all the files and use it for the auto complete.

**Comment by ms-jpq** [comment]
sorry at the moment there is no plan to do this, the easiest way to write a custom source in python is to use an out of box lsp server crate  from pypi and implement the single `textdocument/complete` method on it.

I remember seeing one that does that, not sure what's it call tho.

or you can write an python extension and wrap a single function call using lua.

the reasoning here is purely to prevent any of the `coq`'s code form unnecessary exposure for the purposes of avoiding ossification
