### ISSUE TITLE
cgn does not insert entire completion text

### ISSUE THREAD

**Issue by YodaEmbedding** [ms-jpq/coq_nvim#47]
Running `cgn` on highlighted text and replacing with a completion doesn't work.

Run `*ncgnimp<C-n><CR><Esc>.` on the following:

```python
hello
hello
```

Expected result:
```python
import
import
```

Actual result:
```python
import
imp
```

---

<details>
<summary>Off topic</summary>

Side note: it would be neat to also have vim's default behavior of inserting the completion text without needing to hit enter so it's one less keystroke, i.e. `*ncgnimp<C-n><Esc>.`.

EDIT: I fixed this by overriding the `<CR>` binding:
```vim
inoremap <silent><expr> <Esc> pumvisible() ? (complete_info().selected == -1 ? "\<Esc>" : "\<C-y>\<Esc>") : "\<Esc>"
```

</details>

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/issues/102
