### ISSUE TITLE
Problem with NERDTree

### ISSUE THREAD

**Issue by cipriantarta** [ms-jpq/coq_nvim#471]
For some reason, [this function ](https://github.com/ms-jpq/coq_nvim/blob/9bfdabc2ead2b37ea381a8cad8556b20abe18a76/coq/server/registrants/attachment.py#L50) is causing issues with for NERDTree `Variable name conflicts with existing function: Listener`

I've renamed it locally to `_coq_listener` and all is good, if you want, I can create a PR for that.

**Comment by Bear-03** [comment]
I'm facing this issue as well. As a temporary workaround, is there any way to solve the conflict without having to do rename the function every time the plugin is installed in a machine?

**Comment by vkaracic** [comment]
@cipriantarta I think you should create a PR for this :slightly_smiling_face:
