### ISSUE TITLE
Automatically start?

### ISSUE THREAD

**Issue by poperigby** [ms-jpq/coq_nvim#48]
Is there a more graceful way to start `coq` when vim starts besides `au BufEnter * :COQnow<CR>`, or is that the way I'm supposed to do it?

Edit: I'd also like it if I could get the `No snippets loaded` message to not show. I passed `[--shut-up]`.

**Comment by ms-jpq** [comment]
set `coq_settings.auto_start` to `true`

I just added this due to popular request :), so you will need to update your repo

and the no snippets loaded thing, please set `coq_settings.clients.snippets.enabled` to `false`.

**Comment by heygarrett** [comment]
@ms-jpq Apologies for my ignorance, but how exactly would I do this? I tried `let coq_settings.auto_start = 'true'` in my `init.vim`, but it doesn't seem to work.

**Comment by ms-jpq** [comment]
`let g:coq_settings = { 'auto_start': v:true }`

The `g` here is important, it puts the variable in `global` scope, so `coq` can read it.

and `v:true` should be used instead of `true`. The difference is  akin to`{ "<key>": true }` and ``{ "<key>": "true" }``

**Comment by heygarrett** [comment]
Thanks so much!

**Comment by iverberk** [comment]
Small request: can you make the auto_start setting also use the 'shut up' option, as to not display the row of characters? I think most people want it started automatically in the background, with no visual signs.

**Comment by smjonas** [comment]
I agree with @iverberk, this would be a nice option to have. I could not find a way to set this option when `auto_start` is used (as opposed to calling `COQnow` manually).

**Comment by poperigby** [comment]
@ms-jpq How do I configure that in lua? 

```
local vim.g.coq_settings = { 'auto_start': v:true } 
```
gives me this error:
```
E5113: Error while calling lua chunk: vim.lua:63: /home/cassidy/.config/nvim/lua/options.lua:22: unexpected symbol near '.'
```

**Comment by iverberk** [comment]
This works for me:

```
vim.g.coq_settings = {
  ["auto_start"] = true,
  ["keymap.jump_to_mark"] = "<c-n>",
  ["keymap.bigger_preview"] = "<c-b>",
  ["clients.buffers.enabled"] = false,
  ["clients.snippets.enabled"] = false,
  ["clients.tmux.enabled"] = false,
  ["clients.tree_sitter.enabled"] = false,
}
```

**Comment by PopeRigby** [comment]
Ok that works. Thank you. Is there a way to get rid of the `⭐️ 🥚 🐣 🐓 🐔 ⭐️  Sekoh` message?

**Comment by icyphox** [comment]
+1 for the ‘shut up’ option on `auto_start`.

**Comment by CacheApp25** [comment]
lol 😓 I do apologise.. won't happen again!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/94

`auto_start = 'shut-up'`
