### ISSUE TITLE
Snippet not replacing postfix string properly.

### ISSUE THREAD

**Issue by bachhh** [ms-jpq/coq_nvim#491]
Hi, first of all, thanks for the amazing plugin.

I notice a small snippet bug where the typed word is not entirely replaced by the snippet, but rather just appended into it. This seems only to happen when the end character is also the first character of the snippet ( `printf` -> `fmt.Printf` in the screen recording). I don't have this issue when doing `print` -> `fmt.Printf` 
( using Go with `gopls` LSP backend )

https://user-images.githubusercontent.com/11842798/171109226-42b0b659-e288-4d31-b6a4-c436cfb689d7.mp4

I'm guessing the current behaviour is to look for the matching sub-string of the, stop at the first matched character(s) and try to replace `[index:end]` with the snippet ? But this does not seem to happen with other type source, like when I tested with completion from LSP: 
```go
	facfac1234567 := 0 // new variable
	facfac<Tab>  		// if bug happens I expect the variable name to be facfacfac1234567
	facfac1234567	// but coq still correctly autocomplete the variable's name and replaced the whole string
```

**Comment by bachhh** [comment]
Hi, with some quick logging, I found this:

```
[debug]trans_adjusted(new_text: fmt.Printf("\n"))
[debug] trans(line_before:     printf, line_after :  ,new_text: fmt.Printf("\n"))
[debug] _line_match(lhs:True, existing:"    printf", insertion:"fmt.printf("\n")")
[debug] "fmt.printf("\n")" == "    printf"
[debug] "fmt.printf("\n"" == "    printf"
[debug] "fmt.printf("\n" == "    printf"
[debug] "fmt.printf("\" == "    printf"
[debug] "fmt.printf("" == "    printf"
[debug] "fmt.printf(" == "    printf"
[debug] "fmt.printf" == "    printf"
[debug] "fmt.print" == "   printf"
[debug] "fmt.prin" == "  printf"
[debug] "fmt.pri" == " printf"
[debug] "fmt.pr" == "printf"
[debug] "fmt.p" == "rintf"
[debug] "fmt." == "intf"
[debug] "fmt" == "ntf"
[debug] "fm" == "tf"
[debug] "f" == "f"
```

I'm not entirely sure if this is an intended behaviour, but in `_line_match()` function an iterator of `existing` is moving backwards in an attempts to find any postfix of `existing` that matches the `insertion`.
- For `print -> fmt.Printf("")`, `l_match()` could not found a matching substring of `insertion`, so the whole `existing` is replaced entirely. 

LSP does not show this behaviour is because it does not call `trans()`  at all.

**Comment by bachhh** [comment]
So I think there are 2 things that could be added:

1. In `l_match()`, `existing` is `lstrip()` in combination with `lower()` to help better the pattern matching for snippet
```
# in trans.py
def _line_match(lhs: bool, existing: str, insertion: str) -> str:
    existing, insertion = lower(existing).lstrip(), lower(insertion)
    ...
#output: 
[debug] _line_match(lhs:True, existing:"fmt.print", insertion:"fmt.printf("\n")")
[debug] "fmt.printf("\n")" == "fmt.print"
[debug] "fmt.printf("\n"" == "fmt.print"
[debug] "fmt.printf("\n" == "fmt.print"
[debug] "fmt.printf("\" == "fmt.print"
[debug] "fmt.printf("" == "fmt.print"
[debug] "fmt.printf(" == "fmt.print"
[debug] "fmt.printf" == "fmt.print"
[debug] "fmt.print" == "fmt.print"
```

2. User will utilize the fuzzy behaviour of `coq` to type snippet, my anecdotal example: `printf -> fmt.Printf()`, but this have some problem when the matching will resolve to a sub-optimal matching pattern to replace the `existing` string.

- We can either add a special case to search for middle pattern along side `postfix-prefix` matching
```
# in trans.py
def _line_match(lhs: bool, existing: str, insertion: str) -> str:
    existing, insertion = lower(existing).lstrip(), lower(insertion)
    if lhs:
        if existing.lstrip() in insertion:
            return existing.lstrip()
```

- Or limit the `postfix-prefix` matching to only apply for string with length >= 3 ( or any length > 1) 

```
def _line_match(lhs: bool, existing: str, insertion: str) -> str:
    existing, insertion = lower(existing).lstrip(), lower(insertion)
    if lhs:
        for match in reverse_acc(insertion):
            if len(match) <= 2:
                return ""
            if match == existing[-len(match) :]:
                return match
        else:
            return ""
    else:
        for match in reverse_acc("".join(reversed(insertion))):
            if len(match) <= 2:
                return ""
            if match == existing[: len(match) :]:
                return match
        else:
            return ""
```

**Comment by bachhh** [comment]
Hi with a some logging, I think I found the reason for the issue encountered:

From what I understand, the `_line_match()` function will attempt to match a longest `prefix-postfix` of `existing` with `insertion` string. If a pattern is found, then only that part of `existing` will get replaced. If no patterns found, the whole `existing` string is replaced.
```
[debug] _line_match(lhs:True, existing:"    printf", insertion:"fmt.printf("\n")")
[debug] "fmt.printf("\n")" == "    printf"
[debug] "fmt.printf("\n"" == "    printf"
[debug] "fmt.printf("\n" == "    printf"
[debug] "fmt.printf("\" == "    printf"
[debug] "fmt.printf("" == "    printf"
[debug] "fmt.printf(" == "    printf"
[debug] "fmt.printf" == "    printf"
[debug] "fmt.print" == "   printf"
[debug] "fmt.prin" == "  printf"
[debug] "fmt.pri" == " printf"
[debug] "fmt.pr" == "printf"
[debug] "fmt.p" == "rintf"
[debug] "fmt." == "intf"
[debug] "fmt" == "ntf"
[debug] "fm" == "tf"
[debug] "f" == "f"
```

- In case of `printf -> fmt.Printf`, a not so desirable pattern is matched ( `f` ) where as a better pattern could be matched (`printf`) but excluded since it is neither a prefix or postfix

- In case of `print -> fmt.Printf`, `l_match()` return an empty string so `trans()` just replace the whole `existing` string with `insertion`
- In case of `fmt.printf -> fmt.Printf`, `lmatch()` found the pattern correctly, but I found something a bit odd 
  
```
[debug] _line_match(lhs:True, existing:"    fmt.printf", insertion:"fmt.printf("\n")")
[debug] "fmt.printf("\n")" == "    fmt.printf"
[debug] "fmt.printf("\n"" == "    fmt.printf"
[debug] "fmt.printf("\n" == "    fmt.printf"
[debug] "fmt.printf("\" == "   fmt.printf"
[debug] "fmt.printf("" == "  fmt.printf"
[debug] "fmt.printf(" == " fmt.printf"
[debug] "fmt.printf" == "fmt.printf"
```

When matching with postfix of `existing`, as code is very often indented, the `existing` string will always contain some leading white space. I'm ( naively ) assuming this is not a desirable behaviour.

**Comment by bachhh** [comment]
So I think there are 2 things that could be added:

1. ( I'm not really sure about this ) In `l_match()`, `existing` could be `lstrip()` in combination with `lower()` to help better the pattern matching for snippet
```
# in trans.py
def _line_match(lhs: bool, existing: str, insertion: str) -> str:
    existing, insertion = lower(existing).lstrip(), lower(insertion)
    ...

# This particular example ended up just the same, but I hope it could improve other types of pattern: 

[debug] _line_match(lhs:True, existing:"fmt.print", insertion:"fmt.printf("\n")")
[debug] "fmt.printf("\n")" == "fmt.print"
[debug] "fmt.printf("\n"" == "fmt.print"
[debug] "fmt.printf("\n" == "fmt.print"
[debug] "fmt.printf("\" == "fmt.print"
[debug] "fmt.printf("" == "fmt.print"
[debug] "fmt.printf(" == "fmt.print"
[debug] "fmt.printf" == "fmt.print"
[debug] "fmt.print" == "fmt.print"
```

2. May be can limit the `postfix-prefix` matching to only apply for string with certain length ( min length = 2 ) ?

```
def _line_match(lhs: bool, existing: str, insertion: str) -> str:
    existing, insertion = lower(existing).lstrip(), lower(insertion)
    if lhs:
        for match in reverse_acc(insertion):
            if len(match) <= 2:
                return ""
            if match == existing[-len(match) :]:
                return match
        else:
            return ""
    else:
        for match in reverse_acc("".join(reversed(insertion))):
            if len(match) <= 2:
                return ""
            if match == existing[: len(match) :]:
                return match
        else:
            return ""
```

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/commit/637dd411b709e2b30b848b86930b2e24e4910db8

turns out there is one more bug, the reversed match wasn't being useful, but anyways i fixed it so its all good
