### ISSUE TITLE
Why rename?

### ISSUE THREAD

**Issue by kuator** [ms-jpq/coq_nvim#5]
Why rename? 😡
Unsubscribed

**Comment by ms-jpq** [comment]
sorry i like coq too much :(

evakuator ***@***.***>于2021年5月5日 周三21:13写道：

**Comment by kuator** [comment]
That's okay then, subscribed back
![4pWvVzeZ8Hw](https://user-images.githubusercontent.com/25168308/117242600-64b67900-ae57-11eb-950b-87793e3c7db8.jpg)

**Comment by UltiRequiem** [comment]
@kuator  What was the previous name? 

![image](https://user-images.githubusercontent.com/71897736/129751297-79638c27-9224-4191-ba3e-290395ac4a8a.png)

**Comment by kuator** [comment]
> @kuator What was the previous name?
> 
> ![image](https://user-images.githubusercontent.com/71897736/129751297-79638c27-9224-4191-ba3e-290395ac4a8a.png)

kok.nvim

**Comment by ms-jpq** [comment]
@kuator since ur here,

treesitter just got a preview window :D 

![ts.img](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/treesitter.gif)

**Comment by ms-jpq** [comment]
if github makes their stupid gpt3 thing open source, i will add that next :D

**Comment by UltiRequiem** [comment]
> if github makes their stupid gpt3 thing open source, i will add that next :D

nice
