### ISSUE TITLE
How to show documentation manually?

### ISSUE THREAD

**Issue by anthony-tron** [ms-jpq/coq_nvim#500]
I'm using COQ for autocompleting typescript and it works very well and show the documentation of the current autocomplete option.

But is it possible to show the documentation popup manually?

`coc.nvim` exposes some editor commands to do that (taken from their documentation) : 
```
" Use K to show documentation in preview window.
nnoremap <silent> K :call ShowDocumentation()<CR>

function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction
```

Thank you in advance :)

**Comment by willruggiano** [comment]
`:h vim.lsp.buf.hover()`

**Comment by anthony-tron** [comment]
Thank you that worked :)
