### ISSUE TITLE
Fails in Windows

### ISSUE THREAD

**Issue by eriedaberrie** [ms-jpq/coq_nvim#521]
In Windows, running `:COQnow` throws the error `cannot import name 'open_unix_connection' from 'asyncio'`.
I have Python 3.10.7 and am on the latest commit of the plugin.

**Comment by ms-jpq** [comment]
oh shit fuck ok good to know let me fix

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/commit/9151e5ee2f533333fa48492655482c2b030331f8
