### ISSUE TITLE
Missing autocompletion suggestion after dot

### ISSUE THREAD

**Issue by greasycat** [ms-jpq/coq_nvim#530]
Nvim 0.10.0

```lua

vim.g.coq_settings = { 
    auto_start= 'shut-up',
    clients = {
        lsp = {
            resolve_timeout = 5,
        },
    },
    limits = {
        completion_auto_timeout = 5,
    },
}
```

![image](https://user-images.githubusercontent.com/7360146/195982497-4fd18848-b11b-45a4-8882-dc69982d606d.png)
![image](https://user-images.githubusercontent.com/7360146/195982519-edeb7f50-bd8c-4372-9b31-1ee850f8f43c.png)

After hitting manual completion
![image](https://user-images.githubusercontent.com/7360146/195982520-212b177b-f318-41d3-ab2a-1d80e845fb6a.png)

**Comment by SKrPl** [comment]
Facing the same issue.

**Comment by mauricebutts** [comment]
Here as well

**Comment by Shougo** [comment]
It seems completion_auto_timeout config.

**Comment by ivaaaan** [comment]
Same here with Go

**Comment by dreamerlzl** [comment]
Here as well. But it would later work by deleting the first dot and then try to add a new second dot.
I am using lazy.nvim, and not sure whether that would have impact.

**Comment by SamCB** [comment]
Seems to be related to #464. I've added my config and some debugging I've tried there.

**Comment by wustho** [comment]
Happens to me as well

**Comment by HicaroD** [comment]
```lua
vim.g.coq_settings = { 
    limits = {
        completion_auto_timeout = 0,
    },
}
```

Try setting this config to zero. It will probably work as expected.

Question for @ms-jpq: The default value for `completion_auto_timeout` is 0.266, is there any good reason for this? Why not just set it to 0 as the default value and let the user decide if he wants a timeout or not?

**Comment by Herz3h** [comment]
I confirm @HicaroD solution is working with neovim 0.10.2 and latest of coq_nvim 

PS: I'm new to coq_nvim, and nearly uninstalled it because it didn't work by following the README. I almost thought, plugin is broken. I think it would be nice to set a higher timeout by default and maybe mention it in read me than have so low that there is no autocompletion.

**Comment by ms-jpq** [comment]
fixed

**Comment by ms-jpq** [comment]
the issue was that previously if a client is in the cache, i just don't ask the server for more rows of completion, turns out thats a poor idea...
