### ISSUE TITLE
It is frozen

### ISSUE THREAD

**Issue by CRAG666** [ms-jpq/coq_nvim#536]
![imagen](https://user-images.githubusercontent.com/34254373/201453373-98a7ee1f-3ad2-426a-af31-a25d8e16b611.png)
Coq freezes when I enter an LSP option.I have to close Nvim with Kill to get out of there

**Comment by mad-briller** [comment]
duplicate of: https://github.com/ms-jpq/coq_nvim/issues/531

**Comment by mad-briller** [comment]
this should be fixed as of #531
