### ISSUE TITLE
Any tips on migrating to lazy.nvim?

### ISSUE THREAD

**Issue by ristillu** [ms-jpq/coq_nvim#549]
I have recently migrated from `wbthomason/packer.nvim` to `folke/lazy.nvim`. It has broken my `coq`. The `use` entry has changed and now looks like:

```lua
{
    "ms-jpq/coq_nvim",
    "branch = "coq",
    dependencies = { "ms-jpq/coq.artifacts", branch = "artifacts" },
    config = function() require("config.ms_jpq_coq") end,
    lazy = false,  -- ensure loaded
},
```

The only changes from `packer` are the syntax and the `lazy = false,` line to (I thought) ensure `coq` is loaded. `coq` works if I run `:COQnow`. But in my `config/ms_jpq_coq.lua` file that I'm loading I have 
```lua
vim.g.coq_settings = {
    auto_start = true
}

local lsp = require("lspconfig")
local coq = require("coq")
-- set up servers below with ensure_capabilities etc
```
which is what I had with `packer`, except it is not auto-loading with `lazy`.

I've run with `COQ_DEBUG=1 nvim $file -V10vimlog` and there is nothing in the `:LspLog` or `vimlog` that seems obvious. Just nothing happens until I hit `:COQnow`. In the `vimlog` I can see that `lazy` processes the `coq` entry but it just doesn't load until I command it to. I also added `print("loading coq")` to the `config/ms_jpq_coq.lua` file to confirm that file is loaded, and it is.

Any tips?

**Comment by ristillu** [comment]
In answer to my own question, I figured out if I added `auto_start` to my `init.lua` it behaved as expected, therefore it was some weird ordering thing that `lazy` triggers.

To clean up my code, I removed the `auto_start` from my config for `coq`
```lua
--[[ vim.g.coq_settings = {
     auto_start = true
} ]]

local lsp = require("lspconfig")
local coq = require("coq")
-- set up servers below with ensure_capabilities etc
```

and changed the `lazy` entry to:
```lua
    {
        "ms-jpq/coq_nvim",
        branch = "coq",
        init = function() vim.g.coq_settings = { auto_start = true } end,
        dependencies = {
            { "ms-jpq/coq.artifacts", branch = "artifacts" },
            { "neovim/nvim-lspconfig" },
        },
        config = function() require("config.ms_jpq_coq") end,
        lazy = false,
    },
```
Note the added `init` line.

The `init` happens before the plugin is loaded, ref [here](https://github.com/folke/lazy.nvim#-plugin-spec). I guess the entry for the spec under the `config` part is where the behavior I noticed is implied:

>`config` is executed when the plugin loads. The default implementation will automatically run `require("plugin").setup(opts)`. `"plugin"` will default to `name` if specified, otherwise `lazy.nvim` will do its best to guess the correct plugin name. See also `opts`. To use the default implementation without `opts` set `config` to `true`.

**Comment by OmiChrome** [comment]
@ristillu im getting this error , but coq runs fine? 
![image](https://user-images.githubusercontent.com/108952834/232899492-eff7856f-233f-4225-8dbc-08e980588c52.png)

**Comment by OmiChrome** [comment]
fixed tho

**Comment by ekhodx** [comment]
@NormTurtle um... so... How did you fix this?
