### ISSUE TITLE
Feature: Look-ahead search to be even faster

### ISSUE THREAD

**Issue by npielawski** [ms-jpq/coq_nvim#58]
I am proposing an idea to make coq_nvim even faster, if you feel like it is necessary. The idea is that if we can predict the next keystroke accurately, we could already run the search on the line of code + the predicted character during the idle time between two keystrokes. When the user presses the right keystroke, we just have to display the result instead of doing the search and then displaying.

**Issues to address and make this idea work:**

1. How to predict the next key?

That can be done with various degrees of complexity, if we want to be fast we can use a markov chain fitted on some source code from github. Once fitted on some dataset, it is basically a lookup table. For a given letter, it gives the probability of the next letters following. If I press 'i', then 'm' (import) or ' ' (for i in...) will be likely in python, but not 'y' for instance. What is important is to quantify the hit and miss rate in practice.

2. What happens if we can't predict accurately?
We can run multiple searches on the different most probable next letters. If we press another letter than predicted, we drop the search altogether and fallback to the normal non-predictive version of the search. I suppose it can also be optimized for not completely dropping the search and help the fuzzy search? 

We could have multiple threads running, let's say 4 and they would look for the 4 most likely next keystrokes.

**Example:**
Let's assume only one thread is available at all times.

- I type 'i'
- The engine gives the regular suggestions for 'i'
- There is some idle time, so it predicts that 'm' (10%) and ' ' (5%) are likely, so it searches for 'im' (most likely option)
- I type 'm'
- The engine prints the already searched suggestions for 'im'
- There is some idle time, 'p' is the most likely, so the look-ahead search begins
- I type an 'a' 
- The engine drops the look-ahead search if it is still running and searches on-the-fly for 'ima'

There is already some look ahead going on in the code but I am not certain what it entices, so maybe this - or something similar - is already implemented? Sorry if I just invented the square wheel :)

**Comment by ms-jpq** [comment]
due to GIL, python is effectively single threaded within the same process.

this is not feasible unfortunately. 

The built-in tabnine source is GPT-2 though. and I am not sure if we are gonna get a GPT3 source at some point, if Github open sources their model, I will definitely add it though.
