### ISSUE TITLE
Can we remove "BUF" completion ?

### ISSUE THREAD

**Issue by Watynecc** [ms-jpq/coq_nvim#583]
Like this ?
![image](https://github.com/ms-jpq/coq_nvim/assets/64525273/d869d832-3571-4cd7-8e9b-a136e60ada0d)

**Comment by TheLeoP** [comment]
Add

```lua
vim.g.coq_settings = {
    clients = {
      buffers = {
        enabled = false,
      },
    }
}
```

on your config before `:COQnow`

**Comment by Watynecc** [comment]
Thanks you !
