### ISSUE TITLE
:COQnow throws TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by niiichtsy** [ms-jpq/coq_nvim#585]
Running :COQnow results in the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/neverducky/.local/nvim/site/pack/packer/start/coq_nvim/coq/__main__.py", line 162, in <module>
    from .client import init
  File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/client.py", line 21, in <module>
    from ._registry import ____
  File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/_registry.py", line 2, in <module>
    from .server.registrants import attachment, autocmds, help, marks, noop, omnifunc
  File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/registrants/autocmds.py", line 15, in <module>
    from ...clients.registers.worker import Worker as RegWorker
  File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/registers/worker.py", line 16, in <module>
    async def _registers(names: AbstractSet[str]) -> Mapping[str, str]:
TypeError: 'ABCMeta' object is not subscriptable
```

I don't really know what caused it - I've tried reverting to a known working commit, and the problem remained. Running :COQdeps again did not help.

The fix is pretty simple though - in coq_nvim/coq/clients/registers/worker.py change 

```
from collections.abc import Mapping
from typing import AbstractSet, AsyncIterator, MutableSet
```
to

```
from typing import AbstractSet, AsyncIterator, MutableSet, Mapping
```

as per https://stackoverflow.com/questions/59955751/abcmeta-object-is-not-subscriptable-when-trying-to-annotate-a-hash-variable

Since this is my first issue on GitHub, let me know if I should change sth - maybe this should actually be a pull request?

Hope it helps!

**Comment by opeshm** [comment]
Hi!. I have the same problem, but the solution of changing the import line doesn't work for me.

**Comment by EduardoNeville** [comment]
Hi! Changing the imports did work for me!

> Running :COQnow results in the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/neverducky/.local/nvim/site/pack/packer/start/coq_nvim/coq/__main__.py", line 162, in <module>
>     from .client import init
>   File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/client.py", line 21, in <module>
>     from ._registry import ____
>   File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/_registry.py", line 2, in <module>
>     from .server.registrants import attachment, autocmds, help, marks, noop, omnifunc
>   File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/server/registrants/autocmds.py", line 15, in <module>
>     from ...clients.registers.worker import Worker as RegWorker
>   File "/home/neverducky/.local/share/nvim/site/pack/packer/start/coq_nvim/coq/clients/registers/worker.py", line 16, in <module>
>     async def _registers(names: AbstractSet[str]) -> Mapping[str, str]:
> TypeError: 'ABCMeta' object is not subscriptable
> ```
> 
> I don't really know what caused it - I've tried reverting to a known working commit, and the problem remained. Running :COQdeps again did not help.
> 
> The fix is pretty simple though - in coq_nvim/coq/clients/registers/worker.py change
> 
> ```
> from collections.abc import Mapping
> from typing import AbstractSet, AsyncIterator, MutableSet
> ```
> 
> to
> 
> ```
> from typing import AbstractSet, AsyncIterator, MutableSet, Mapping
> ```
> 
> as per https://stackoverflow.com/questions/59955751/abcmeta-object-is-not-subscriptable-when-trying-to-annotate-a-hash-variable
> 
> Since this is my first issue on GitHub, let me know if I should change sth - maybe this should actually be a pull request?
> 
> Hope it helps!

**Comment by opeshm** [comment]
To retry this workaround, I deleted all my configuration and started from scratch. Then I changed the imports and now it works. Thanks.
> Hi!. I have the same problem, but the solution of changing the import line doesn't work for me.
