### ISSUE TITLE
RTP not found

### ISSUE THREAD

**Issue by mTvare6** [ms-jpq/coq_nvim#61]
When running the plugin as mentioned in the readme, when starting it it says, `RTP not found` from `lua/coq.lua` in 9th line

**Comment by moorecode** [comment]
I had this issue, I'm using Packer and I missed an important detail in the README:
```lua
vim.schedule(function ()
  local lsp = require "lspconfig"
  require("packer").loader("coq_nvim coq.artifacts")
  lsp.<server>.setup(require("coq")().lsp_ensure_capabilities(<stuff...>))
end)
```

I did not initially have the setup code wrapped in `vim.schedule(function () ... end)`.
Here is whats currently in my init.lua:
```lua
local lsp_servers = { "pyright" }
local on_attach = function....
vim.schedule(function ()
  require("packer").loader("coq_nvim coq.artifacts")
  for _, lsp in ipairs(lsp_servers) do
    nvim_lsp[lsp].setup(
      require("coq")().lsp_ensure_capabilities({ on_attach = on_attach })
    )
  end
end)
```

Keep an eye on this PR, looks like this config may change at some point: https://github.com/ms-jpq/coq_nvim/pull/53

**Comment by ms-jpq** [comment]
should be fixed by now, i will close it unless people still have issues
