### ISSUE TITLE
how to remove default <C-k> keybinding

### ISSUE THREAD

**Issue by rendivs925** [ms-jpq/coq_nvim#644]

**Comment by joey-scanga** [comment]
I'd like to know as well

**Comment by joey-scanga** [comment]
@rendi12345678 this worked for me:

```
vim.g.coq_settings = {
    keymap = {
        bigger_preview = "null"
    },
}
```

**Comment by rendivs925** [comment]
> @rendi12345678 this worked for me:
> 
> ```
> vim.g.coq_settings = {
>     keymap = {
>         bigger_preview = "null"
>     },
> }
> ```

it works perfectly sir
