### ISSUE TITLE
Is there a way to disable the `BUF` suggestions?

### ISSUE THREAD

**Issue by Stopfield** [ms-jpq/coq_nvim#649]
So, I just want to see results from the LSP. Is there a way to disable the `BUF` suggestions?
I checked the help but nothing interesting got my eye.

**Comment by Shougo** [comment]
You can disable any source by this.

https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SOURCES.md#coq_settingsclientsxenabled

**Comment by Stopfield** [comment]
Thanks! I think the project could improve the docs, I got really lost.
Also, just an idea, maybe COQ could use vimdocs with the `:help` command. I don't know why it uses its own command.

**Comment by Stopfield** [comment]
Thanks! I think the project could improve the docs, I got really lost.
Also, just an idea, maybe COQ could use vimdocs with the `:help` command. I don't know why it uses its own command
