### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by UltiRequiem** [ms-jpq/coq_nvim#65]
This works:

```lua
require("lspconfig").pyright.setup(coq.lsp_ensure_capabilities({}))
```
But no snippets:

![image](https://user-images.githubusercontent.com/71897736/129750117-4046bc7a-a3a4-4621-aee7-3d0c78b6787e.png)

But this dont
```lua
vim.schedule(function ()
  local lsp = require "lspconfig"
  require("packer").loader("coq_nvim coq.artifacts")
  lsp.pyright.setup(require("coq")().lsp_ensure_capabilities({}))
end)
```

What I'm doing wrong?

![image](https://user-images.githubusercontent.com/71897736/129749819-5b5abf89-7d7f-463d-84bd-e7a7a108a39f.png)

**Comment by ms-jpq** [comment]
humm weird, can you please pull latest and try again?

```lua
use { 'ms-jpq/coq_nvim', branch = 'coq'} -- main one
use { 'ms-jpq/coq.artifacts', branch= 'artifacts'} -- 9000+ Snippets
```

I just pushed a bunch of changes and hopefully you can just do:

```lua
local lsp = require "lspconfig"
local coq = require "coq" -- add this

lsp.<server>.setup(<stuff...>)                              -- before
lsp.<server>.setup(coq.lsp_ensure_capabilities(<stuff...>)) -- after
```

**Comment by heygarrett** [comment]
After pulling the most recent changes I'm not getting any snippet suggestions, but I'm also not getting any errors. Current setup:

``` lua
local nvim_lsp = require 'lspconfig'
local coq = require 'coq'

local servers = { 'pyright', 'rust_analyzer', 'sourcekit' }
for _, lsp in ipairs(servers) do
	nvim_lsp[lsp].setup(coq.lsp_ensure_capabilities({}))
end
```

Edit: coq wasn't auto-starting, so it looks like `let g:coq_settings = { 'auto_start': v:true }` may not be working.

**Comment by heygarrett** [comment]
If I uninstall `coq.artifacts` I get the `No snippets loaded` prompt mentioned in the initial issue. I even tried using nvim-lspconfig recommended setup for snippets support:

``` lua
local nvim_lsp = require 'lspconfig'
local coq = require 'coq'

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

local servers = { 'pyright', 'rust_analyzer', 'sourcekit' }
for _, lsp in ipairs(servers) do
	nvim_lsp[lsp].setup(coq.lsp_ensure_capabilities({
		capabilities = capabilities
	}))
end
```
