### ISSUE TITLE
How to enable Tabnine?

### ISSUE THREAD

**Issue by UltiRequiem** [ms-jpq/coq_nvim#66]
I have tied whit:
```lua
vim.g.coq_settings.clients.tabnine.enabled = true
```
But:
![image](https://user-images.githubusercontent.com/71897736/129751758-6577cdba-d041-4856-bff6-ac04dc45d21c.png)

**Comment by UltiRequiem** [comment]
Fixed:
```lua
vim.g.coq_settings = { auto_start = true, ["clients.tabnine.enabled"] = true }
```

But more documentation is needed, how can I help?

**Comment by beauwilliams** [comment]
Thanks for this
