### ISSUE TITLE
(inline) `cid` and `uid` desynchronization causes valid results to be ignored for third party sources

### ISSUE THREAD

**Issue by TheLeoP** [ms-jpq/coq_nvim#669]
I have a coupe of custom sources and I noticed that sometimes I don't get a suggestion even though my custom source calls `cb(items)` with the suggestion I'm expecting. I'm debugging the issue and I've found that.

1. In the lua side, there is a **single** `cid` that is persistent between different request in order to ignore old requests/responses

https://github.com/ms-jpq/coq_nvim/blob/a23759c0d6f48f5b6b5b1504f24d2021fb87f374/lua/coq/lsp-request.lua#L34

2. If the `uid` sent by the python side is greater than the current `cid` . The whole `acc` for third party sources is reset

https://github.com/ms-jpq/coq_nvim/blob/a23759c0d6f48f5b6b5b1504f24d2021fb87f374/lua/coq/lsp-request.lua#L76-L78

3. The `uid` comes from the python side, is an incremental integer and **depends on the name of the async_request** (i.e. `lsp_inline_third_party`, `lsp_comp`, `lsp_thirdparty`, etc)

https://github.com/ms-jpq/coq_nvim/blob/a23759c0d6f48f5b6b5b1504f24d2021fb87f374/coq/lsp/requests/request.py#L141

What I'm seeing when the results are ignored is something like the following.

1. There is a session for `lsp_third_party` with `uid` 1 that adds results for `acc`
2. There is a session for `lsp_inline_third_party` with `uid` 3 that removes all the results in `acc`
3. Completion shows no results

I can't reliably reproduce the error, it has something to do with timming. If I add a bunch of prints on the lua side that clover `:messages`, it happens more reliably. My (not so well informed) guess is that either

1. `lsp_inline_third_party` can be requested mutliple times per completion request, so its `uid` can grow faster than the others
2. ~the original dessign for `acc` didn't account for the fact that `uid` may come from different names (`lsp_inline_third_party` reseting the `uid` for `lsp_third_party`). If this is the case, using a table to store different `cid` for different names (simillar to how `acc` stores different resutls for different named third party sources) may be a solution. But, currently, the name where the uid is coming from is not being passed from the python side to the lua side~. this didn't work

Note: I've reproduced/tracked down this bug only with third party sources, but it may also be affecting regular LSP sources (?)

**Comment by TheLeoP** [comment]
For example, if I log `uid` and `name` in

https://github.com/ms-jpq/coq_nvim/blob/a23759c0d6f48f5b6b5b1504f24d2021fb87f374/coq/lsp/requests/request.py#L141

I get the following

```
async_request uid, name: 0 lsp_inline_third_party
async_request uid, name: 1 lsp_inline_third_party
async_request uid, name: 0 lsp_comp
async_request uid, name: 0 lsp_third_party
async_request uid, name: 1 lsp_comp
async_request uid, name: 2 lsp_inline_third_party
async_request uid, name: 1 lsp_third_party
async_request uid, name: 2 lsp_comp
async_request uid, name: 3 lsp_inline_third_party
async_request uid, name: 2 lsp_third_party
async_request uid, name: 3 lsp_comp
async_request uid, name: 4 lsp_inline_third_party
async_request uid, name: 3 lsp_third_party
async_request uid, name: 5 lsp_inline_third_party
async_request uid, name: 4 lsp_comp
async_request uid, name: 4 lsp_third_party
async_request uid, name: 6 lsp_inline_third_party
```

The last time the completion got manually triggered, I got not results because `lsp_inline_third_party` with an `uid` of 6 caused all of my custom results to get deleted. If I keep manually triggering the completion, it can keep failling several consecutive completions, but sometimes it starts working again.

I think that there is a race condition. If a high enought `uid` is the last one, all the completions are lost. But, if a low `uid` is the last one, it works as expected.

**Comment by TheLeoP** [comment]
Disabling both inline sources by 

```lua
        third_party_inline = {
          enabled = false,
        },
        lsp_inline = {
          enabled = false,
        },
```

seems to be a workaround

**Comment by ms-jpq** [comment]
oh yeah this is a bug, nice I think i know how to fix. ty!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/commit/70a6f406f7d83dfe66abe33e3687d0ce470ddbd6

should work, please LMK if it doesnt fix anything.

thanks so much for looking into this

**Comment by TheLeoP** [comment]
> thanks so much for looking into this

Thanks to you for looking into the bug c:

> should work, please LMK if it doesnt fix anything.

It works better, but it still fails sometimes. If I add

```lua
vim.print({uid=uid, cid=cids[name], name=name})
```
in

https://github.com/ms-jpq/coq_nvim/blob/70a6f406f7d83dfe66abe33e3687d0ce470ddbd6/lua/coq/lsp-request.lua#L76-L77

I see the following at startup (even before entering insert mode, maybe triggered after entering a buffer/window)

```
{
  name = "lsp_inline_third_party",
  uid = 0
}
{
  name = "lsp_inline_comp",
  uid = 0
}
```

I don't see similar messages for any other `name` (until a completion is requested).

The logs for all `name`s on a completion without results (that should have results) look like

```
{
  cid = 0,
  name = "lsp_third_party",
  uid = 1
}
{
  cid = 1,
  name = "lsp_third_party",
  uid = 1
}
{
  cid = 1,
  name = "lsp_third_party",
  uid = 1
}
{
  cid = 1,
  name = "lsp_third_party",
  uid = 1
}
{
  cid = 1,
  name = "lsp_third_party",
  uid = 1
}
{
  cid = 1,
  name = "lsp_third_party",
  uid = 1
}
{
  cid = 2,
  name = "lsp_inline_third_party",
  uid = 3
}
{
  cid = 2,
  name = "lsp_inline_comp",
  uid = 3
}
{
  cid = 0,
  name = "lsp_comp",
  uid = 1
}
```

It looks like having separate `cid`s, but a shared `acc` is a problem (`lsp_inline_third_party`, `lsp_inline_comp` and `lsp_comp` trigger the `uid > (cids[name] or -1)` condition that resets the value of `acc` even though the `lsp_third_party` requests are not old). I guess that the previous implementation (with the shared cid) should work if the initial request of the `inline` clients is removed to keep them in sync with all the other clients (but I don't know where that request is coming from)

**Comment by ms-jpq** [comment]
thanks i've separated out the acc by method name.

I will do a thorough test when im off of work :)

**Comment by TheLeoP** [comment]
Separatings the `acc`s seems to have solved the problem for now, awesome. Once again thanks for your help and your time c:

**Comment by ms-jpq** [comment]
thank you so much for investigating!
