### ISSUE TITLE
Coq_nvim crashing on launch 

### ISSUE THREAD

**Issue by Klvxn** [ms-jpq/coq_nvim#670]
"This seems to be a problem with symlinks. The sql script it is trying to call is a symbolic link, but it seems you have to explicitly specify `core.symlinks` as `true` to create the symlink when cloning, which vimplug does not do. For anyone using `vimplug` my quick solution is just go into the `nvim-data/plugged` folder, remove the `coq_nvim` directory, open any terminal as administrator (e.g. CMD, Windows Powershell, Git Bash) and manually clone the repo with `git -c core.symlinks=true clone https://github.com/ms-jpq/coq_nvim.git`."

_Originally posted by @54m43lJ in https://github.com/ms-jpq/coq_nvim/issues/589#issuecomment-1651436348_

**Comment by ms-jpq** [comment]
fixed i derefed all the symlinks, thanks for looking into this
