### ISSUE TITLE
Is it possible to suppress notifications on "correspondence"?

### ISSUE THREAD

**Issue by euglevi** [ms-jpq/coq_nvim#674]
Every time the pum opens with the list of items for completion, I receive a notification saying which "corrispondenza" (in Italian) the selected item is. For instance, if the pum opens with 20 items, it says "corrispondenza 1 di 20". When I select the next one, I get "2 di 20" and so on. The notification is shown even with only 1 correspondence or with no one. 

Now my question is: is it possible to suppress this notification? It shows up a lot and it is quite confusing, so it would be great if it is possible to hide it somehow. I could not find any documentation related to this, but could it be that maybe I did not look hard enough?

**Comment by Shougo** [comment]
Hm...  It is `set shortmess-=c`?

```
	  c	don't give |ins-completion-menu| messages; for		*shm-c*
		example, "-- XXX completion (YYY)", "match 1 of 2", "The only
		match", "Pattern not found", "Back at original", etc.
```

**Comment by euglevi** [comment]
Thank you! I did not know about the `shortmess` option. Maybe we should consider setting it by default in coq_nvim. Just a small note if anyone has the same problem: to suppress those notifications it is `set shortmess+=c` rather than `set shortmess-=c`. I will close the issue.
