### ISSUE TITLE
Unusably long error message when using NeoGit

### ISSUE THREAD

**Issue by ryanbas21** [ms-jpq/coq_nvim#70]
When leaving a neogit buffer, sometimes I get an unusably long error message.

I mean I've been hitting 'q' and 'down' for over a minute. It won't go away.

![Screen Shot 2021-08-17 at 10 09 12 AM](https://user-images.githubusercontent.com/18267769/129761900-96ccc63d-a485-4077-ae60-4d5505a20efd.png)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/73
should fix i think

**Comment by ms-jpq** [comment]
So what happens should be that since everything is async, by the time some temp buff is closed and happen to trigger a write event, `coq.nvim` tries to fetch some metadata about that buffer.

but the buffer is closed already, so it errors out.
