### ISSUE TITLE
Auto imports not triggering for typescript

### ISSUE THREAD

**Issue by callebstrom** [ms-jpq/coq_nvim#71]
The plugin seems to work very well (and most importantly, fast as fuck) however, I can't seem to get the auto imports to work. I probably messed something up but I can't quite figure out what. Auto import works fine for me today via the built-in nvim LSP + [`lspinstall`](https://github.com/kabouzeid/nvim-lspinstall) + [`compe`](https://github.com/hrsh7th/nvim-compe) so I think my LSP integration works as it should.

OS: OSX and Linux

After removing `compe` and trying to get auto imports using `coq` I end up with this:
![image](https://user-images.githubusercontent.com/5937782/129759189-e678c0be-c191-46be-9069-96dd91bfeab8.png)

`coq` properly prints the correct import path in the pum footer but when I press enter to complete and add the import, the import is never added (although the symbol is auto completed properly). I run this very minimal `coq` lua config and use the default keybinds:
```lua
local coq = require('coq')
...
nvim_lsp[lsp].setup(coq().lsp_ensure_capabilities(lsp_config))
```

Is this a known issue or do I need to do some deep-diving to figure out what is up with my setup?

**Comment by callebstrom** [comment]
Seems to be working fine for Python though

**Comment by ms-jpq** [comment]
which `pyhon` lsp do you use?

i think i misunderstood the LSP specs and there are actually two ways to import the headers, and I only did one way, so only about half the servers work.

My best guess on the other method is I need to make an additional request to LSP before I apply the edits, so they can import.

That is pretty simple to do though, i will add that in later tonight.

**Comment by callebstrom** [comment]
For python I use `pyright-langserver`. 

That would be amazing, can't wait for this to work so I can start using this plugin full-time. Thank you!

**Comment by ms-jpq** [comment]
ok this is the next issue i will work on, had some other higher priority issues

**Comment by ms-jpq** [comment]
by work on i mean tomorrow, cuz its 2am right now

by now*, ok i need to sleep

**Comment by ahmadov** [comment]
I have the same problem. The `auto-import` feature works fine for C++ but not for TypeScript/JavaScript.

I'm using this LSP: https://github.com/typescript-language-server/typescript-language-server

**Comment by ms-jpq** [comment]
PR https://github.com/ms-jpq/coq_nvim/pull/107 should close this.

please try it, this adds the secondary resolving of LSP completions.

`coq_settings.clients.lsp.resolve_timeout` controls the timeout for the secondary resolving. I think the default is roughly ok, but might be a bit low.

If LSP servers do not respond within the timeout, no headers will be imported.

**Comment by ahmadov** [comment]
@ms-jpq for me it works now. Thanks for a quick fix!

**Comment by ms-jpq** [comment]
SORRY I BROKE SOMETHING IN **THE LAST PR**

https://github.com/ms-jpq/coq_nvim/pull/108

please pull the latest for tix

**Comment by callebstrom** [comment]
Great stuff, works for me! :tada:

**Comment by edmbn** [comment]
Anybody have their dotfiles public? I have made everything work but automatic imports are not working. Tried all the things I read, as incrementing resolve timeout but nothing. I need to see a full example of someone implementing it but haven't find many information. Thank you!

**Comment by minusf** [comment]
auto header import for python does not seem to be working with `pylsp`, but a quick search did not reveal if it supports this feature or not.

**Comment by xiaonengmiao** [comment]
> Anybody have their dotfiles public? I have made everything work but automatic imports are not working. Tried all the things I read, as incrementing resolve timeout but nothing. I need to see a full example of someone implementing it but haven't find many information. Thank you!

Me too. Everything seems to be working except for header imports shown [here](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/lsp_import.gif). I use pyright lsp.
