### ISSUE TITLE
Autocomplete not displaying character before and after LSP

### ISSUE THREAD

**Issue by SamuelTJackson** [ms-jpq/coq_nvim#76]
Hey,
my autocomplete window looks like this:
![image](https://user-images.githubusercontent.com/14303082/129799785-78443b7e-b466-4daf-ac50-d0c785f4c0c6.png)
Do you have an idea what am I missing?

**Comment by ms-jpq** [comment]
You dont have the right fonts.

please set `coq_settings.display.pum.source_context` to something like `["[", "]"]`.

The default values are `["「", "」"]`, because i watched too much [AYAYAYAYYYY](https://www.youtube.com/watch?v=XUhVCoTsBaM).

**Comment by ms-jpq** [comment]
in lua, its something like

```lua
vim.g.coq_settings = {"display.pum.source_context" = {"[", "]"}}
```
