### ISSUE TITLE
How do I setup highlighting in the preview popup?

### ISSUE THREAD

**Issue by poperigby** [ms-jpq/coq_nvim#79]
I want it to look pretty (:

**Comment by ms-jpq** [comment]
humm, it uses builtin syntax highlighting for almost everything.


ie. a preview for `lua` file will have its content highlighted by `lua` syntax.

the only exception is if the LSP server specifies: "use markdown instead".

---

there is nothing user configurable except by changing their own theme.

if you are not seeing pretty colours, its probably the LSP server asking for markdown plain text or something
