### ISSUE TITLE
Consistency: Default mapping should use <C-BS> instead of <BS> for selection completion

### ISSUE THREAD

**Issue by matu3ba** [ms-jpq/coq_nvim#81]
Reasoning: For selection one needs to press `<C-n>` and `<C-p>` anyway. Manual completion also needs `<C-Space>`.

Having `<BS>` without `<C>` feels awkward, since it is 2 key-movements instead of one.

**Comment by zeertzjq** [comment]
In some terminal emulators `<C-BS>`  and `<C-H>` are the same.

**Comment by ms-jpq** [comment]
Sorry no changing of defaults is considered, unless it has very good justifications.

We do not want our existing users to go wtf the next time they update
