### ISSUE TITLE
What is the use case for the AGP bot?

### ISSUE THREAD

**Issue by jdhao** [ms-jpq/coq_nvim#83]
I saw that every day, the agp bot pushes commit to this repo, but it actually does nothing. What is the use for that agp bot? To keep this repo active or it has real usage?

**Comment by ms-jpq** [comment]
it keeps all my repos active so even if i dont commit to a repo in 60 days github still runs the CI.

if my CI breaks, (and it has been broken before) I can fix immediately, or at least know exactly when it broke.

its much easier to hunt down breaking changes if you can pinpoint a date.

just go through your dependencies and see if they did something funny

**Comment by lynndylanhurley** [comment]
@ms-jpq can you just use scheduled events for github actions?

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events

**Comment by max397574** [comment]
@ms-jpq see above
