### ISSUE TITLE
How to customize the symbols used to indicate the source of completions?

### ISSUE THREAD

**Issue by IndianBoy42** [ms-jpq/coq_nvim#87]

**Comment by Shougo** [comment]
I think the screeshot is helpful.

**Comment by IndianBoy42** [comment]
By default it looks like:
![image](https://user-images.githubusercontent.com/5981889/130033825-6bc52089-7b86-45ab-9eb2-065030151f0e.png)

Previously with nvim-compe I did this and it would change the part in `[]`
![image](https://user-images.githubusercontent.com/5981889/130033927-c31a5ae8-edc5-480e-94d7-f1564f8b0839.png)

In general is it possible to customize the things on the right hand side?

**Comment by ms-jpq** [comment]
i can add this fairly easily! :)

its a bit lower priority because its kinda a cosmetic thing though.

**Comment by ms-jpq** [comment]
will do this one soon

stub PR here https://github.com/ms-jpq/coq_nvim/pull/166

**Comment by ms-jpq** [comment]
ok the PR is in, I just need some good defaults for the icons, right now the defaults are just [empty mappings](https://github.com/ms-jpq/coq_nvim/blob/0ae5737a5ab6e20778b021ef46019121c2cb043d/config/defaults.yml#L63)

@IndianBoy42, your screenshot looked really nice, i hope you won't mind posting the mappings used here?

thanks!

**Comment by ms-jpq** [comment]
![图片](https://user-images.githubusercontent.com/50598611/131417014-57da9df2-0a1b-4c89-bcf1-0702a462a99f.png)

https://github.com/ms-jpq/coq_nvim/pull/172

**Comment by IndianBoy42** [comment]
Thanks for the feature 

My nvim config is [here](https://github.com/IndianBoy42/LunarVim.git), you can find those symbols in `lua/lsp/init.lua`

**Comment by ghost** [comment]
@ms-jpq nice feature, but how are you supposed to **change** the icons by yourself?

**Comment by ms-jpq** [comment]
@iRealistiX 

https://github.com/ms-jpq/coq_nvim/blob/coq/docs/DISPLAY.md

:)
