### ISSUE TITLE
Shut up on autostart

### ISSUE THREAD

**Issue by jesse-c** [ms-jpq/coq_nvim#89]
There's the `--shut-up` flag for `:COQnow`, but when using the `auto_start` option, I haven't been able to find a way to mute the welcome message.

Have I missed it, or would it need to be added?

**Comment by rudotriton** [comment]
it will be added

**Comment by jesse-c** [comment]
Yay. Thank you!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/94

`auto_start = 'shut-up'`

**Comment by jesse-c** [comment]
You're amazing. Thank you!
