### ISSUE TITLE
Path completion on windows

### ISSUE THREAD

**Issue by TheLeoP** [ms-jpq/coq_nvim#95]
Could be possible to use path autocompletion with fordwardslash, "/", instead of just with backslash, "\" on Windows? I know that paths on Dos and on Unix like systems behave differently, but I was wondering if this was possible. I have no idea how the plugin works internally, so I don't know if what I'm asking for may be stupid.

Also, thank you, by the way. Your plugin runs fast as fuck on my 10 year old mini laptop and I really apreatte your effort for making that possible.

**Comment by ms-jpq** [comment]
no this is very possible, i should add it in as a feature 👍

**Comment by ms-jpq** [comment]
it is a feature now
https://github.com/ms-jpq/coq_nvim/pull/98

**Comment by TheLeoP** [comment]
Today I was trying this new feature and, could it be possibble to also expand the completion with fordward-slash and not with backslash?

**Comment by ms-jpq** [comment]
sure i can add that as an option i guess

**Comment by ms-jpq** [comment]
##### `coq_settings.clients.paths.path_seps`

Which seperator chars to use. Empty for default. Must be `/` under unix and `/` or `\` for windows.

**default:**

```json
[]
```

https://github.com/ms-jpq/coq_nvim/pull/109

**Comment by TheLeoP** [comment]
I'm not sure if this is the intended behaviour, but If I set "/" as the path_seps, it triggers completions, but when I choose a directory, it expands the path with a "\" at the end.

Could it be possible to expand the completion also using the path_seps variable?

Also, sorry for not trying this feature early.

**Comment by ms-jpq** [comment]
fucking knew it. i was gonna add this but then decided to 💤

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/218

**Comment by TheLeoP** [comment]
Thaaaanks :3. But I'm still having the same issue.


https://user-images.githubusercontent.com/53507599/132075929-c8c42dfc-376b-4761-a7bb-7fc564d33d03.mp4

On the bottom of the window you can see my coq config.

**Comment by ms-jpq** [comment]
oh shit sorry, i fixed something else entirely instead, LOL

**Comment by ms-jpq** [comment]
ima go to the mall with frens, so ill fix later

**Comment by ms-jpq** [comment]
the issue is i made a call to join(), didnt realize it also normalized windows paths

**Comment by TheLeoP** [comment]
Good luck at the mall. I will be here to try the next fix and, hopefully, I won't take 14 days to do it this time, lol

**Comment by ms-jpq** [comment]
i regret eating mall sushi

**Comment by TheLeoP** [comment]
I hope the sushi didn't make you sick :c

**Comment by ms-jpq** [comment]
it did 🐸

**Comment by TheLeoP** [comment]
I expect you cuold get some rest and recover

**Comment by ms-jpq** [comment]
sorry about the long wait, I was focused on getting [snippet live repl](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SNIPS.md) done,

now that its finished, i will take a look at your issue after work tmr :)

**Comment by TheLeoP** [comment]
Don't worry, I can wait. Thanks again :3
Also, I just tried the new snippets feature on my ususal Windows desktop and on my Ubuntu laptop and I found a problem on Windows, so I'm going to create a new Issue for that.

**Comment by ms-jpq** [comment]
is it path again? LOL

**Comment by TheLeoP** [comment]
I'm not sure. On Ubuntu all the snippets work perfectrly, but on Windows none of them work.

**Comment by TheLeoP** [comment]
I have just created the issue with all the information #236

**Comment by ms-jpq** [comment]
ok thanks!

god damn i hate windows lol,

**Comment by ms-jpq** [comment]
sorry about the inconvenience

**Comment by TheLeoP** [comment]
Well, I'm using your software for free, so I feel weird getting an apologize, but there is no problem. And, again, thanks for also supporting Windows 👉👈.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/237

please see if it works

**Comment by TheLeoP** [comment]
Yes, it works 🥳
