### ISSUE TITLE
Pad the floating preview window with space

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#96]
The floating preview window isn't padded with space, which may look a bit strange if the code around has the same foreground color as text in the preview window:

![Screenshot_20210820_071340](https://user-images.githubusercontent.com/35768171/130156034-544f4d62-68e4-4317-aea5-68f6c4450121.png)

The Neovim built-in hover handler for comparison:

![Screenshot_20210820_071413](https://user-images.githubusercontent.com/35768171/130156045-52d31f4e-8ccb-491b-ae55-d2ff227fda7b.png)

**Comment by ms-jpq** [comment]
good idea!

**Comment by doums** [comment]
I confirm !

**Comment by zeertzjq** [comment]
Neovim builtin hover handler seems to use this:

```lua
      border = {
        { '', 'NormalFloat' },
        { '', 'NormalFloat' },
        { '', 'NormalFloat' },
        { ' ', 'NormalFloat' },
        { '', 'NormalFloat' },
        { '', 'NormalFloat' },
        { '', 'NormalFloat' },
        { ' ', 'NormalFloat' },
      },
```

**Comment by ms-jpq** [comment]
yeah im gonna use the built ins, will take a bit of redoing the math

**Comment by ms-jpq** [comment]
<img width="453" alt="图片" src="https://user-images.githubusercontent.com/50598611/130555857-9d60aac0-f3a6-4cae-9a31-95431f067379.png">

https://github.com/ms-jpq/coq_nvim/pull/127

**Comment by doums** [comment]
Hi @ms-jpq, great, but if I may, you should let the user the choice of the configuration for the window border (most plugin do).

You can accept the builtin config table for the border:

>                               • `border`: Style of (optional) window border. This can
>                                either be a string or an array. The string
>                                values are
>                               • "none": No border (default).
>                                • "single": A single line box.
>                                • "double": A double line box.
>                                • "rounded": Like "single", but with rounded
>                                  corners ("╭" etc.).
>                                • "solid": Adds padding by a single whitespace
>                                  cell.
>                                • "shadow": A drop shadow effect by blending
>                                  with the background.
>                                • If it is an array, it should have a length
>                                  of eight or any divisor of eight. The array
>                                  will specifify the eight chars building up
>                                  the border in a clockwise fashion starting
>                                  with the top-left corner. As an example, the
>                                  double box style could be specified as [
>                                  "╔", "═" ,"╗", "║", "╝", "═", "╚", "║" ]. If
>                                  the number of chars are less than eight,
>                                  they will be repeated. Thus an ASCII border
>                                  could be specified as [ "/", "-", "\\", "|"
>                                  ], or all chars the same as [ "x" ]. An
>                                  empty string can be used to turn off a
>                                  specific border, for instance, [ "", "", "",
>                                  ">", "", "", "", "<" ] will only make
>                                  vertical borders but not horizontal ones. By
>                                  default, `FloatBorder` highlight is used,
>                                  which links to `VertSplit` when not defined.
>                                  It could also be specified by character: [
>                                  {"+", "MyCorner"}, {"x", "MyBorder"} ].

That way you can pass it directly to the function `nvim_open_win` (or whatever the api function you use).

**Comment by zeertzjq** [comment]
Maybe [`get_border_size()`](https://github.com/neovim/neovim/blob/32024787b6b1ef39c23bda1653c23b5dfbde9e81/runtime/lua/vim/lsp/util.lua#L49) can be useful (it's a private function though). I translated that function in <https://github.com/ms-jpq/pynvim_pp/pull/1/>.

**Comment by zeertzjq** [comment]
#132 depends on <https://github.com/ms-jpq/pynvim_pp/pull/1>.

**Comment by ms-jpq** [comment]
today is my anniversary, ill go merge in ur stuff later ok @zeertzjq , thank you so much 💯

**Comment by ms-jpq** [comment]
and i forgot flowers reeeeeeeeeeee

**Comment by ms-jpq** [comment]
merged thanks to @zeertzjq

**Comment by doums** [comment]
I just added to the config
```
  ['display.preview.border'] = {'', '', '', ' ', '', '', '', ' '},
```
awesome, thanks @zeertzjq and @ms-jpq !
