### ISSUE TITLE
How to rewrite CompletionItemKind?

### ISSUE THREAD

**Issue by ChrisAmelia** [ms-jpq/coq_nvim#97]
When setting the `CompletionItemKind`:

```lua
local custom_attach = function()
    require'vim.lsp.protocol'.CompletionitemKind = {
        '';
        'ƒ';
    }
end

lsp.gopls.setup(coq.lsp_ensure_capabilities({
    on_attach = custom_attach()
    ... -- other configs
}))
```

This doesn't seem do the trick.

**Comment by ms-jpq** [comment]
wait so is this about wanting to use custom icons?

that should be coming as a feature. you can't over write it like this, `coq.nvim` uses a pre-compiled list from like the latest version of `nvim`, so out dated nvim installations can also benefit from upstream changes.

so overwriting `CompletionitemKind` doesn't work.

**Comment by ms-jpq** [comment]
duplicate https://github.com/ms-jpq/coq_nvim/issues/87,

will do this one soon since its pretty simple

**Comment by ms-jpq** [comment]
![icons.png](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/icons.png)

**Comment by mcchrish** [comment]
I think default should be no icons as most don't install a patched font.

**Comment by ms-jpq** [comment]
haha i figured i would try my luck on this one and see if it passes the scream test.

l0l

🐸

**Comment by mcchrish** [comment]
I don't want mario "?" boxes in my editor.

**Comment by ms-jpq** [comment]
please `let g:coq_settings = { 'display.icons.mode': 'none' }`.

sorry u had to be the first victim.

**Comment by mcchrish** [comment]
I'll try that.
I plan to map my own icons anyway just using basic characters shipped with the font. There's probably a math symbol that is close enough.
